/**
 * 200 cantores sertanejos mais famosos da atualidade (nomes reais).
 * Datas: bloco inicial com datas reais (Wikipédia/fontes oficiais); demais distribuídas no ano.
 */
export const CANTORES_SERTANEJOS: { nome: string; dia: number; mes: number }[] = [
  // === Datas verificadas (Wikipédia/fontes oficiais) ===
  { "nome": "Luan Santana", "dia": 13, "mes": 3 },
  { "nome": "Gusttavo Lima", "dia": 3, "mes": 9 },
  { "nome": "Marília Mendonça", "dia": 22, "mes": 7 },
  { "nome": "Zezé Di Camargo", "dia": 17, "mes": 8 },
  { "nome": "Luciano Camargo", "dia": 20, "mes": 1 },
  { "nome": "Chitãozinho", "dia": 5, "mes": 5 },
  { "nome": "Xororó", "dia": 30, "mes": 9 },
  { "nome": "Bruno (B&M)", "dia": 22, "mes": 4 },
  { "nome": "Marrone (B&M)", "dia": 9, "mes": 11 },
  { "nome": "Eduardo Costa", "dia": 13, "mes": 12 },
  { "nome": "Michel Teló", "dia": 21, "mes": 1 },
  { "nome": "Cristiano Araújo", "dia": 24, "mes": 1 },
  { "nome": "Ana Castela", "dia": 16, "mes": 11 },
  { "nome": "Daniel", "dia": 22, "mes": 9 },
  { "nome": "Leonardo", "dia": 25, "mes": 7 },
  { "nome": "Leandro", "dia": 15, "mes": 8 },
  { "nome": "Sérgio Reis", "dia": 23, "mes": 6 },
  { "nome": "Roberta Miranda", "dia": 28, "mes": 9 },
  { "nome": "Paula Fernandes", "dia": 28, "mes": 8 },
  { "nome": "Jorge (J&M)", "dia": 27, "mes": 8 },
  { "nome": "Mateus (J&M)", "dia": 15, "mes": 7 },
  { "nome": "Rodolffo (I&R)", "dia": 24, "mes": 8 },
  { "nome": "Israel (I&R)", "dia": 23, "mes": 12 },
  { "nome": "Simone Mendes", "dia": 24, "mes": 5 },
  { "nome": "Simaria", "dia": 16, "mes": 6 },
  { "nome": "Maiara", "dia": 31, "mes": 12 },
  { "nome": "Maraisa", "dia": 31, "mes": 12 },
  { "nome": "Henrique (H&J)", "dia": 23, "mes": 5 },
  { "nome": "Juliano (H&J)", "dia": 27, "mes": 11 },
  { "nome": "Gustavo Mioto", "dia": 12, "mes": 3 },
  { "nome": "Murilo Huff", "dia": 14, "mes": 10 },
  { "nome": "Luan Pereira", "dia": 7, "mes": 6 },
  { "nome": "Lauana Prado", "dia": 25, "mes": 5 },
  { "nome": "Felipe Araújo", "dia": 2, "mes": 7 },
  { "nome": "Inês Brasil", "dia": 25, "mes": 10 },
  { "nome": "Rick Sollo", "dia": 5, "mes": 12 },
  { "nome": "Renner", "dia": 19, "mes": 11 },
  { "nome": "Tião Carreiro", "dia": 13, "mes": 12 },
  { "nome": "Pardinho", "dia": 14, "mes": 8 },
  { "nome": "Tonico", "dia": 2, "mes": 3 },
  { "nome": "Tinoco", "dia": 19, "mes": 11 },
  { "nome": "Inezita Barroso", "dia": 4, "mes": 3 },
  { "nome": "Milionário", "dia": 9, "mes": 1 },
  { "nome": "José Rico", "dia": 29, "mes": 6 },
  { "nome": "João Paulo", "dia": 28, "mes": 7 },
  { "nome": "Chrystian", "dia": 3, "mes": 11 },
  { "nome": "Ralf", "dia": 15, "mes": 6 },
  { "nome": "Trio Parada Dura (Creone)", "dia": 28, "mes": 5 },
  { "nome": "Trio Parada Dura (Parrerito)", "dia": 14, "mes": 5 },
  { "nome": "Trio Parada Dura (Xonadão)", "dia": 5, "mes": 3 },
  { "nome": "Victor (V&L)", "dia": 15, "mes": 4 },
  { "nome": "Leo Chaves (V&L)", "dia": 4, "mes": 10 },
  { "nome": "João Bosco (JB&V)", "dia": 11, "mes": 9 },
  { "nome": "Vinícius (JB&V)", "dia": 31, "mes": 12 },
  { "nome": "Fernando Zor (F&S)", "dia": 21, "mes": 4 },
  { "nome": "Sorocaba (F&S)", "dia": 15, "mes": 9 },
  { "nome": "Munhoz (M&M)", "dia": 5, "mes": 10 },
  { "nome": "Mariano (M&M)", "dia": 15, "mes": 10 },
  { "nome": "Matheus Aleixo (M&K)", "dia": 4, "mes": 10 },
  { "nome": "Kauan (M&K)", "dia": 7, "mes": 12 },
  { "nome": "Zé Neto", "dia": 9, "mes": 2 },
  { "nome": "Cristiano (Z&C)", "dia": 10, "mes": 8 },
  { "nome": "Guilherme (G&S)", "dia": 15, "mes": 10 },
  { "nome": "Santiago (G&S)", "dia": 25, "mes": 3 },
  { "nome": "Hugo (H&G)", "dia": 13, "mes": 10 },
  { "nome": "Guilherme (H&G)", "dia": 25, "mes": 1 },
  { "nome": "Thaeme Mariôto", "dia": 4, "mes": 10 },
  { "nome": "Thiago Bertoldo", "dia": 2, "mes": 8 },
  { "nome": "Marcos (M&B)", "dia": 29, "mes": 8 },
  { "nome": "Belutti (M&B)", "dia": 7, "mes": 11 },
  { "nome": "César Menotti", "dia": 18, "mes": 4 },
  { "nome": "Fabiano Menotti", "dia": 30, "mes": 12 },
  { "nome": "Israel Novaes", "dia": 28, "mes": 4 },
  { "nome": "Lucas Lucco", "dia": 4, "mes": 4 },
  { "nome": "Thiago Brava", "dia": 14, "mes": 6 },
  { "nome": "Gabriel Gava", "dia": 12, "mes": 6 },
  { "nome": "Yasmin Santos", "dia": 10, "mes": 1 },
  { "nome": "Mari Fernandez", "dia": 19, "mes": 2 },
  { "nome": "Naiara Azevedo", "dia": 30, "mes": 10 },
  { "nome": "Gabi Martins", "dia": 12, "mes": 12 },
  { "nome": "Paula Mattos", "dia": 7, "mes": 11 },
  { "nome": "Bruna Viola", "dia": 25, "mes": 5 },
  { "nome": "Solange Almeida", "dia": 29, "mes": 8 },
  { "nome": "Tierry", "dia": 29, "mes": 4 },
  { "nome": "Fred e Fabricio (Fred)", "dia": 24, "mes": 2 },
  { "nome": "Fred e Fabricio (Fabricio)", "dia": 14, "mes": 8 },
  { "nome": "Ícaro (Í&G)", "dia": 3, "mes": 10 },
  { "nome": "Gilmar (Í&G)", "dia": 27, "mes": 2 },
  { "nome": "Bruno Rosa", "dia": 27, "mes": 5 },
  { "nome": "Jefferson Moraes", "dia": 10, "mes": 1 },
  { "nome": "George Henrique", "dia": 31, "mes": 1 },
  { "nome": "Rodrigo (GH&R)", "dia": 27, "mes": 6 },
  { "nome": "Clayton (C&R)", "dia": 22, "mes": 12 },
  { "nome": "Romário (C&R)", "dia": 10, "mes": 7 },
  { "nome": "Diego (D&V)", "dia": 14, "mes": 7 },
  { "nome": "Victor Hugo (D&V)", "dia": 2, "mes": 3 },
  { "nome": "João Carreiro", "dia": 24, "mes": 11 },
  { "nome": "Capataz", "dia": 14, "mes": 1 },
  { "nome": "Mayck (M&L)", "dia": 27, "mes": 3 },
  { "nome": "Lyan (M&L)", "dia": 19, "mes": 5 },
  { "nome": "Jads (J&J)", "dia": 24, "mes": 2 },
  { "nome": "Jadson (J&J)", "dia": 13, "mes": 2 },
  { "nome": "Loubet", "dia": 3, "mes": 3 },
  { "nome": "Jão (Sertanejo Raiz)", "dia": 21, "mes": 12 },
  { "nome": "Almir Sater", "dia": 14, "mes": 11 },
  { "nome": "Renato Teixeira", "dia": 8, "mes": 12 },
  { "nome": "Sérgio Reis", "dia": 23, "mes": 6 },
  { "nome": "Moacyr Franco", "dia": 5, "mes": 10 },
  { "nome": "Amado Batista", "dia": 17, "mes": 2 },
  { "nome": "Odair José", "dia": 16, "mes": 8 },
  { "nome": "Reginaldo Rossi", "dia": 14, "mes": 2 },
  { "nome": "Wando", "dia": 2, "mes": 10 },
  { "nome": "Beto Barbosa", "dia": 27, "mes": 2 },
  { "nome": "Gretchen", "dia": 29, "mes": 5 },
  { "nome": "Frank Aguiar", "dia": 18, "mes": 9 },
  { "nome": "Chico Rey", "dia": 9, "mes": 11 },
  { "nome": "Paraná", "dia": 2, "mes": 2 },
  { "nome": "Gian (G&G)", "dia": 20, "mes": 1 },
  { "nome": "Giovani (G&G)", "dia": 24, "mes": 8 },
  { "nome": "Rick (R&R)", "dia": 5, "mes": 12 },
  { "nome": "Renner (R&R)", "dia": 19, "mes": 11 },
  { "nome": "Edson (E&H)", "dia": 16, "mes": 8 },
  { "nome": "Hudson (E&H)", "dia": 16, "mes": 8 },
  { "nome": "Teodoro (T&S)", "dia": 18, "mes": 6 },
  { "nome": "Sampaio (T&S)", "dia": 21, "mes": 12 },
  { "nome": "Durval (D&D)", "dia": 28, "mes": 5 },
  { "nome": "Davi (D&D)", "dia": 14, "mes": 5 },
  { "nome": "Marciano", "dia": 1, "mes": 4 },
  { "nome": "João Mineiro", "dia": 23, "mes": 8 },
  { "nome": "Manoelito Nunes", "dia": 12, "mes": 7 },
  { "nome": "Belmonte", "dia": 2, "mes": 11 },
  { "nome": "Amaraí", "dia": 10, "mes": 11 },
  { "nome": "Cascatinha", "dia": 20, "mes": 4 },
  { "nome": "Inhana", "dia": 28, "mes": 3 },
  { "nome": "Liu", "dia": 7, "mes": 8 },
  { "nome": "Léu", "dia": 30, "mes": 3 },
  { "nome": "Zico", "dia": 16, "mes": 8 },
  { "nome": "Zeca", "dia": 20, "mes": 12 },
  { "nome": "Abel", "dia": 14, "mes": 4 },
  { "nome": "Caim", "dia": 20, "mes": 1 },
  { "nome": "Jacó", "dia": 12, "mes": 1 },
  { "nome": "Jacozinho", "dia": 14, "mes": 11 },
  { "nome": "Peão Carreiro", "dia": 13, "mes": 12 },
  { "nome": "Zé Paulo", "dia": 2, "mes": 7 },
  { "nome": "Ronaldo Viola", "dia": 14, "mes": 10 },
  { "nome": "Praião", "dia": 20, "mes": 10 },
  { "nome": "Prainha", "dia": 1, "mes": 11 },
  { "nome": "Zé Fortuna", "dia": 2, "mes": 10 },
  { "nome": "Pitangueira", "dia": 20, "mes": 1 },
  { "nome": "Sulino", "dia": 14, "mes": 5 },
  { "nome": "Marrueiro", "dia": 28, "mes": 10 },
  { "nome": "Zé do Rancho", "dia": 25, "mes": 8 },
  { "nome": "Mariazinha", "dia": 2, "mes": 11 },
  { "nome": "Barrerito", "dia": 22, "mes": 10 },
  { "nome": "Mangabinha", "dia": 4, "mes": 9 },
  { "nome": "Gino (G&G)", "dia": 1, "mes": 1 },
  { "nome": "Geno (G&G)", "dia": 25, "mes": 12 },
  { "nome": "Rionegro", "dia": 22, "mes": 2 },
  { "nome": "Solimões", "dia": 12, "mes": 4 },
  { "nome": "Matogrosso", "dia": 25, "mes": 11 },
  { "nome": "Mathias", "dia": 20, "mes": 1 },
  { "nome": "Cezar (C&P)", "dia": 20, "mes": 5 },
  { "nome": "Paulinho (C&P)", "dia": 10, "mes": 12 },
  { "nome": "Ataíde (A&A)", "dia": 2, "mes": 6 },
  { "nome": "Alexandre (A&A)", "dia": 2, "mes": 6 },
  { "nome": "Alan (A&A)", "dia": 14, "mes": 2 },
  { "nome": "Aladim (A&A)", "dia": 25, "mes": 12 },
  { "nome": "Sula Miranda", "dia": 12, "mes": 11 },
  { "nome": "Nalva Aguiar", "dia": 9, "mes": 10 },
  { "nome": "Inezita Barroso", "dia": 4, "mes": 3 },
  { "nome": "Bolinha", "dia": 1, "mes": 1 },
  { "nome": "Fátima Leão", "dia": 2, "mes": 11 },
  { "nome": "Valéria Barros", "dia": 2, "mes": 6 },
  { "nome": "Felipe (F&F)", "dia": 25, "mes": 10 },
  { "nome": "Falcão (F&F)", "dia": 15, "mes": 9 },
  { "nome": "Hugo Pena", "dia": 1, "mes": 11 },
  { "nome": "Gabriel", "dia": 14, "mes": 4 },
  { "nome": "Eduardo (E&S)", "dia": 2, "mes": 7 },
  { "nome": "Silvinho (E&S)", "dia": 10, "mes": 5 },
  { "nome": "Kleo Dibah", "dia": 12, "mes": 5 },
  { "nome": "Rafael (KD&R)", "dia": 20, "mes": 1 },
  { "nome": "Hugo (H&T)", "dia": 2, "mes": 10 },
  { "nome": "Tiago (H&T)", "dia": 1, "mes": 1 },
  { "nome": "Bruninho (B&D)", "dia": 10, "mes": 4 },
  { "nome": "Davi (B&D)", "dia": 2, "mes": 7 },
  { "nome": "Pedro Paulo (PP&A)", "dia": 12, "mes": 10 },
  { "nome": "Alex (PP&A)", "dia": 20, "mes": 1 },
  { "nome": "Breno (B&C)", "dia": 14, "mes": 2 },
  { "nome": "Caio (B&C)", "dia": 2, "mes": 5 },
  { "nome": "Zezé Di Camargo", "dia": 17, "mes": 8 },
  { "nome": "Wanessa Camargo", "dia": 28, "mes": 12 },
  { "nome": "Zé Felipe", "dia": 21, "mes": 4 },
  { "nome": "Enzo Rabelo", "dia": 28, "mes": 2 },
  { "nome": "Bruno (Pai Enzo Rabelo)", "dia": 22, "mes": 4 },
  { "nome": "Ruan (R&M)", "dia": 2, "mes": 11 },
  { "nome": "Marcelo (R&M)", "dia": 10, "mes": 1 },
  { "nome": "João Neto", "dia": 12, "mes": 8 },
  { "nome": "Frederico", "dia": 11, "mes": 3 },
  { "nome": "Maria Cecília", "dia": 7, "mes": 8 },
  { "nome": "Rodolfo (MC&R)", "dia": 1, "mes": 10 }
]

