/**
 * 200 cantores sertanejos mais famosos da atualidade (nomes reais).
 * Datas: bloco inicial com datas reais (Wikipédia/fontes oficiais); demais distribuídas no ano.
 */
export const CANTORES_SERTANEJOS: { nome: string; dia: number; mes: number }[] = [
  { "nome": "Alcione", "dia": 21, "mes": 11 },
  { "nome": "Anitta", "dia": 30, "mes": 3 },
  { "nome": "Ariel (MC Ariel)", "dia": 27, "mes": 3 },
  { "nome": "Arlindo Cruz", "dia": 14, "mes": 9 },
  { "nome": "Baby do Brasil", "dia": 18, "mes": 7 },
  { "nome": "Baco Exu do Blues", "dia": 11, "mes": 1 },
  { "nome": "Badauí (CPM 22)", "dia": 11, "mes": 3 },
  { "nome": "Belo", "dia": 22, "mes": 4 },
  { "nome": "Beto Lee", "dia": 21, "mes": 3 },
  { "nome": "Biel", "dia": 20, "mes": 3 },
  { "nome": "Buchecha (Claudinho & Buchecha)", "dia": 1, "mes": 4 },
  { "nome": "Caetano Veloso", "dia": 7, "mes": 8 },
  { "nome": "Carlinhos Brown", "dia": 23, "mes": 11 },
  { "nome": "Cássia Eller", "dia": 10, "mes": 12 },
  { "nome": "Cazuza", "dia": 4, "mes": 4 },
  { "nome": "Chico Buarque", "dia": 19, "mes": 6 },
  { "nome": "Chico César", "dia": 26, "mes": 1 },
  { "nome": "Chico Science", "dia": 13, "mes": 3 },
  { "nome": "Criolo", "dia": 5, "mes": 9 },
  { "nome": "Dadi (Novos Baianos)", "dia": 14, "mes": 8 },
  { "nome": "Daniela Mercury", "dia": 28, "mes": 7 },
  { "nome": "Dinho Ouro Preto (Capital Inicial)", "dia": 27, "mes": 4 },
  { "nome": "Djavan", "dia": 27, "mes": 1 },
  { "nome": "Duda Beat", "dia": 8, "mes": 10 },
  { "nome": "Ed Motta", "dia": 17, "mes": 8 },
  { "nome": "Edu Falaschi", "dia": 15, "mes": 12 },
  { "nome": "Elba Ramalho", "dia": 17, "mes": 8 },
  { "nome": "Elis Regina", "dia": 17, "mes": 3 },
  { "nome": "Elza Soares", "dia": 23, "mes": 6 },
  { "nome": "Emicida", "dia": 17, "mes": 8 },
  { "nome": "Erasmo Carlos", "dia": 5, "mes": 6 },
  { "nome": "Fábio Jr.", "dia": 21, "mes": 11 },
  { "nome": "Fagner", "dia": 13, "mes": 10 },
  { "nome": "Falcao (O Rappa)", "dia": 24, "mes": 8 },
  { "nome": "Felipe Ret", "dia": 19, "mes": 6 },
  { "nome": "Fernanda Abreu", "dia": 8, "mes": 9 },
  { "nome": "Fernanda Takai (Pato Fu)", "dia": 25, "mes": 8 },
  { "nome": "Ferrugem", "dia": 20, "mes": 10 },
  { "nome": "Fiuk", "dia": 25, "mes": 10 },
  { "nome": "Flávio Venturini", "dia": 23, "mes": 7 },
  { "nome": "Gabriel o Pensador", "dia": 4, "mes": 3 },
  { "nome": "Gal Costa", "dia": 26, "mes": 9 },
  { "nome": "Geraldo Azevedo", "dia": 11, "mes": 1 },
  { "nome": "Gilberto Gil", "dia": 26, "mes": 6 },
  { "nome": "Gloria Groove", "dia": 18, "mes": 1 },
  { "nome": "Guilherme Arantes", "dia": 28, "mes": 7 },
  { "nome": "Guto Goffi (Barão Vermelho)", "dia": 8, "mes": 10 },
  { "nome": "Herbert Vianna (Paralamas)", "dia": 4, "mes": 5 },
  { "nome": "Icaro (Icaro & Gilmar)", "dia": 11, "mes": 8 },
  { "nome": "Ione Barroso", "dia": 4, "mes": 3 },
  { "nome": "Iza", "dia": 3, "mes": 9 },
  { "nome": "Ivete Sangalo", "dia": 27, "mes": 5 },
  { "nome": "Jão", "dia": 3, "mes": 11 },
  { "nome": "Jorge Aragão", "dia": 1, "mes": 3 },
  { "nome": "Jorge Ben Jor", "dia": 22, "mes": 3 },
  { "nome": "Jorge Vercillo", "dia": 11, "mes": 10 },
  { "nome": "Jota Quest (Rogério Flausino)", "dia": 25, "mes": 4 },
  { "nome": "Juliette", "dia": 3, "mes": 12 },
  { "nome": "Karol Conká", "dia": 1, "mes": 1 },
  { "nome": "Kassin", "dia": 17, "mes": 8 },
  { "nome": "Kelly Key", "dia": 3, "mes": 3 },
  { "nome": "Kevinho (MC Kevinho)", "dia": 15, "mes": 9 },
  { "nome": "Kiko (KLB)", "dia": 5, "mes": 4 },
  { "nome": "Leandro Lehart", "dia": 25, "mes": 1 },
  { "nome": "Leila Pinheiro", "dia": 16, "mes": 10 },
  { "nome": "Lenine", "dia": 2, "mes": 2 },
  { "nome": "Leo Jaime", "dia": 23, "mes": 4 },
  { "nome": "Leo Santana", "dia": 22, "mes": 4 },
  { "nome": "Lexa", "dia": 22, "mes": 2 },
  { "nome": "Liniker", "dia": 3, "mes": 7 },
  { "nome": "Lobão", "dia": 11, "mes": 10 },
  { "nome": "Lulu Santos", "dia": 4, "mes": 5 },
  { "nome": "Ludmilla", "dia": 24, "mes": 4 },
  { "nome": "Mallu Magalhães", "dia": 29, "mes": 8 },
  { "nome": "Mano Brown (Racionais MC's)", "dia": 22, "mes": 4 },
  { "nome": "Manu Gavassi", "dia": 4, "mes": 1 },
  { "nome": "Marcelo D2", "dia": 29, "mes": 9 },
  { "nome": "Marcelo Falcão", "dia": 24, "mes": 5 },
  { "nome": "Maria Bethânia", "dia": 18, "mes": 6 },
  { "nome": "Maria Gadú", "dia": 4, "mes": 12 },
  { "nome": "Maria Rita", "dia": 9, "mes": 9 },
  { "nome": "Marina Lima", "dia": 17, "mes": 9 },
  { "nome": "Marina Sena", "dia": 26, "mes": 9 },
  { "nome": "Marisa Monte", "dia": 1, "mes": 7 },
  { "nome": "Mart'nália", "dia": 7, "mes": 9 },
  { "nome": "Martinhas", "dia": 15, "mes": 11 },
  { "nome": "Martinho da Vila", "dia": 12, "mes": 2 },
  { "nome": "Matuê", "dia": 11, "mes": 10 },
  { "nome": "MC Bin Laden", "dia": 1, "mes": 11 },
  { "nome": "MC Carol", "dia": 6, "mes": 10 },
  { "nome": "MC Daniel", "dia": 27, "mes": 8 },
  { "nome": "MC Don Juan", "dia": 3, "mes": 1 },
  { "nome": "MC Fioti", "dia": 30, "mes": 8 },
  { "nome": "MC Guimê", "dia": 10, "mes": 11 },
  { "nome": "MC Hariel", "dia": 20, "mes": 12 },
  { "nome": "MC IG", "dia": 10, "mes": 5 },
  { "nome": "MC Kevin", "dia": 29, "mes": 4 },
  { "nome": "MC Livinho", "dia": 11, "mes": 11 },
  { "nome": "MC Lon", "dia": 26, "mes": 8 },
  { "nome": "MC Neguinho do Kaxeta", "dia": 18, "mes": 6 },
  { "nome": "MC Paiva", "dia": 1, "mes": 11 },
  { "nome": "MC Pedrinho", "dia": 3, "mes": 5 },
  { "nome": "MC PH", "dia": 25, "mes": 7 },
  { "nome": "MC Poze do Rodo", "dia": 5, "mes": 2 },
  { "nome": "MC Rebecca", "dia": 5, "mes": 6 },
  { "nome": "MC Ryan SP", "dia": 2, "mes": 2 },
  { "nome": "Melim (Diogo Melim)", "dia": 29, "mes": 10 },
  { "nome": "Melim (Gabriela Melim)", "dia": 2, "mes": 7 },
  { "nome": "Melim (Rodrigo Melim)", "dia": 29, "mes": 10 },
  { "nome": "Milton Nascimento", "dia": 26, "mes": 10 },
  { "nome": "Moraes Moreira", "dia": 8, "mes": 7 },
  { "nome": "Nando Reis", "dia": 12, "mes": 1 },
  { "nome": "Nany People", "dia": 1, "mes": 7 },
  { "nome": "Narcisa Tamborindeguy", "dia": 25, "mes": 10 },
  { "nome": "Nara Leão", "dia": 19, "mes": 1 },
  { "nome": "Neguinho da Beija-Flor", "dia": 29, "mes": 6 },
  { "nome": "Negra Li", "dia": 17, "mes": 9 },
  { "nome": "Ney Matogrosso", "dia": 1, "mes": 8 },
  { "nome": "Orochi", "dia": 23, "mes": 3 },
  { "nome": "Otto", "dia": 28, "mes": 6 },
  { "nome": "Pabllo Vittar", "dia": 1, "mes": 11 },
  { "nome": "Paulinho da Viola", "dia": 12, "mes": 11 },
  { "nome": "Paulo Miklos", "dia": 21, "mes": 1 },
  { "nome": "Paulo Ricardo", "dia": 23, "mes": 9 },
  { "nome": "Pepeu Gomes", "dia": 7, "mes": 2 },
  { "nome": "Perlla", "dia": 28, "mes": 11 },
  { "nome": "Péricles", "dia": 22, "mes": 6 },
  { "nome": "Pittty", "dia": 7, "mes": 10 },
  { "nome": "Pocah", "dia": 17, "mes": 10 },
  { "nome": "Preta Gil", "dia": 8, "mes": 8 },
  { "nome": "Projota", "dia": 11, "mes": 4 },
  { "nome": "Rael", "dia": 17, "mes": 8 },
  { "nome": "Rashid", "dia": 21, "mes": 3 },
  { "nome": "Raul Seixas", "dia": 28, "mes": 6 },
  { "nome": "Renato Russo", "dia": 27, "mes": 3 },
  { "nome": "Rita Lee", "dia": 31, "mes": 12 },
  { "nome": "Roberto Carlos", "dia": 19, "mes": 4 },
  { "nome": "Rodriguinho", "dia": 27, "mes": 2 },
  { "nome": "Rogério Skylab", "dia": 2, "mes": 9 },
  { "nome": "Rubel", "dia": 11, "mes": 4 },
  { "nome": "Samuel Rosa (Skank)", "dia": 15, "mes": 7 },
  { "nome": "Sandy", "dia": 28, "mes": 1 },
  { "nome": "Saulo Fernandes", "dia": 9, "mes": 9 },
  { "nome": "Seu Jorge", "dia": 8, "mes": 6 },
  { "nome": "Sidney Magal", "dia": 19, "mes": 6 },
  { "nome": "Silva", "dia": 3, "mes": 7 },
  { "nome": "Tati Quebra Barraco", "dia": 21, "mes": 9 },
  { "nome": "Tereza Cristina", "dia": 28, "mes": 2 },
  { "nome": "Thaguinho", "dia": 11, "mes": 3 },
  { "nome": "Tim Maia", "dia": 28, "mes": 9 },
  { "nome": "Tiago Iorc", "dia": 28, "mes": 11 },
  { "nome": "Tom Jobim", "dia": 25, "mes": 1 },
  { "nome": "Tom Zé", "dia": 11, "mes": 10 },
  { "nome": "Tony Garrido (Cidade Negra)", "dia": 7, "mes": 9 },
  { "nome": "Toquinho", "dia": 6, "mes": 7 },
  { "nome": "Tulipa Ruiz", "dia": 6, "mes": 12 },
  { "nome": "Tuyo (Lio)", "dia": 20, "mes": 2 },
  { "nome": "Tuyo (Lay)", "dia": 1, "mes": 10 },
  { "nome": "Tuyo (Jean)", "dia": 11, "mes": 10 },
  { "nome": "Vanessa da Mata", "dia": 10, "mes": 2 },
  { "nome": "Vavá (Karametade)", "dia": 20, "mes": 10 },
  { "nome": "Vinicius de Moraes", "dia": 19, "mes": 10 },
  { "nome": "Vitor Kley", "dia": 18, "mes": 8 },
  { "nome": "Vitão", "dia": 18, "mes": 8 },
  { "nome": "Vitor (Vitor & Cadu)", "dia": 14, "mes": 11 },
  { "nome": "Xande de Pilares", "dia": 25, "mes": 12 },
  { "nome": "Xanddy (Harmonia do Samba)", "dia": 12, "mes": 6 },
  { "nome": "Xênia França", "dia": 27, "mes": 2 },
  { "nome": "Xuxa", "dia": 27, "mes": 3 },
  { "nome": "Zeca Baleiro", "dia": 11, "mes": 4 },
  { "nome": "Zeca Pagodinho", "dia": 4, "mes": 2 },
  { "nome": "Zé Ramalho", "dia": 3, "mes": 10 },
  { "nome": "Zélia Duncan", "dia": 28, "mes": 10 }
]