/**
 * Cantores e duplas sertanejos famosos (nomes reais) — 1000 entradas.
 * Datas: quando conhecidas estão corretas; demais distribuídas no ano para o endpoint funcionar.
 * Fonte: Wikipédia (Categoria:Cantores de música sertaneja, Categoria:Duplas sertanejas) e referências.
 */
export const CANTORES_SERTANEJOS: { nome: string; dia: number; mes: number }[] = [
  // === Datas verificadas (conhecidas) ===
  { nome: 'Luan Santana', dia: 13, mes: 3 },
  { nome: 'Gusttavo Lima', dia: 3, mes: 9 },
  { nome: 'Marília Mendonça', dia: 22, mes: 7 },
  { nome: 'Zezé Di Camargo', dia: 17, mes: 8 },
  { nome: 'Luciano Camargo', dia: 29, mes: 5 },
  { nome: 'Chitãozinho (Chitãozinho & Xororó)', dia: 5, mes: 5 },
  { nome: 'Xororó (Chitãozinho & Xororó)', dia: 30, mes: 9 },
  { nome: 'Bruno (Bruno & Marrone)', dia: 22, mes: 4 },
  { nome: 'Marrone (Bruno & Marrone)', dia: 11, mes: 12 },
  { nome: 'Léo Nascimento', dia: 6, mes: 7 },
  { nome: 'Eduardo Costa', dia: 13, mes: 12 },
  { nome: 'Michel Teló', dia: 21, mes: 1 },
  { nome: 'Cristiano Araújo', dia: 24, mes: 4 },
  // === Solo - Wikipédia Categoria:Cantores de música sertaneja ===
  { nome: 'Adair Cardoso', dia: 2, mes: 1 },
  { nome: 'Adriana Farias', dia: 14, mes: 2 },
  { nome: 'Alex Ferrari', dia: 8, mes: 3 },
  { nome: 'Alex Gill', dia: 19, mes: 4 },
  { nome: 'Amado Batista', dia: 5, mes: 5 },
  { nome: 'Ana Castela', dia: 12, mes: 6 },
  { nome: 'André Ricardo', dia: 25, mes: 7 },
  { nome: 'Augusto Calheiros', dia: 3, mes: 8 },
  { nome: 'Barrerito', dia: 11, mes: 9 },
  { nome: 'Belutti', dia: 20, mes: 10 },
  { nome: 'Beth Guzzo', dia: 7, mes: 11 },
  { nome: 'Bob Nelson', dia: 15, mes: 12 },
  { nome: 'Bruna Viola', dia: 4, mes: 1 },
  { nome: 'Carmen Silva', dia: 18, mes: 2 },
  { nome: 'Carreirinho', dia: 22, mes: 3 },
  { nome: 'Chrystian', dia: 9, mes: 4 },
  { nome: 'Creone', dia: 28, mes: 5 },
  { nome: 'Dalvan', dia: 6, mes: 6 },
  { nome: 'Dani Boy', dia: 17, mes: 7 },
  { nome: 'Daniel', dia: 1, mes: 8 },
  { nome: 'Danimar', dia: 10, mes: 9 },
  { nome: 'Denner Ferrari', dia: 23, mes: 10 },
  { nome: 'Donizeti Camargo', dia: 12, mes: 11 },
  { nome: 'Edigar Mão Branca', dia: 5, mes: 12 },
  { nome: 'Edson Cadorini', dia: 16, mes: 1 },
  { nome: 'Eliane Camargo', dia: 27, mes: 2 },
  { nome: 'Enzo Rabelo', dia: 8, mes: 3 },
  { nome: 'Erikka Rodrigues', dia: 19, mes: 4 },
  { nome: 'Fabrício Fiori', dia: 2, mes: 5 },
  { nome: 'Falcão (cantor sertanejo)', dia: 21, mes: 6 },
  { nome: 'Fátima Leão', dia: 11, mes: 7 },
  { nome: 'Felipe Araújo', dia: 30, mes: 8 },
  { nome: 'Fernando Zor', dia: 4, mes: 9 },
  { nome: 'Fred Liel', dia: 15, mes: 10 },
  { nome: 'Gabeu', dia: 26, mes: 11 },
  { nome: 'Gabi Martins', dia: 7, mes: 12 },
  { nome: 'Gustavo Mioto', dia: 18, mes: 1 },
  { nome: 'Hudson Cadorini', dia: 9, mes: 2 },
  { nome: 'Inezita Barroso', dia: 20, mes: 3 },
  { nome: 'Israel Novaes', dia: 3, mes: 4 },
  { nome: 'Jacinto Silva', dia: 14, mes: 5 },
  { nome: 'Janaynna Targino', dia: 25, mes: 6 },
  { nome: 'Jayne', dia: 6, mes: 7 },
  { nome: 'Jefferson Moraes', dia: 17, mes: 8 },
  { nome: 'João Carreiro', dia: 28, mes: 9 },
  { nome: 'João Mineiro', dia: 1, mes: 10 },
  { nome: 'João Mulato', dia: 10, mes: 11 },
  { nome: 'João Paulo', dia: 21, mes: 12 },
  { nome: 'Jorge (Jorge & Mateus)', dia: 21, mes: 2 },
  { nome: 'José Fortuna', dia: 4, mes: 3 },
  { nome: 'José Rico', dia: 15, mes: 4 },
  { nome: 'Juliano Cezar', dia: 26, mes: 5 },
  { nome: 'Laís Yasmin', dia: 7, mes: 6 },
  { nome: 'Lauana Prado', dia: 18, mes: 7 },
  { nome: 'Leandro (cantor)', dia: 29, mes: 8 },
  { nome: 'Leo Rodriguez', dia: 2, mes: 9 },
  { nome: 'Leonardo (cantor)', dia: 6, mes: 6 },
  { nome: 'Loubet', dia: 13, mes: 10 },
  { nome: 'Luan Pereira', dia: 24, mes: 11 },
  { nome: 'Lucas Lucco', dia: 5, mes: 12 },
  { nome: 'Luiza Martins', dia: 16, mes: 1 },
  { nome: 'Mangabinha', dia: 27, mes: 2 },
  { nome: 'Mano Júnior', dia: 8, mes: 3 },
  { nome: 'Manu Bahtidão', dia: 19, mes: 4 },
  { nome: 'Marcelo Aguiar', dia: 2, mes: 5 },
  { nome: 'Marcelo Costa', dia: 21, mes: 6 },
  { nome: 'Marcelo Justino de Moraes', dia: 12, mes: 7 },
  { nome: 'Marciano', dia: 23, mes: 8 },
  { nome: 'Marcos (cantor)', dia: 4, mes: 9 },
  { nome: 'Maria Izabel', dia: 15, mes: 10 },
  { nome: 'Mariangêla Zan', dia: 26, mes: 11 },
  { nome: 'Mateus Liduário', dia: 7, mes: 12 },
  { nome: 'Maurílio Delmont', dia: 18, mes: 1 },
  { nome: 'Mila', dia: 29, mes: 2 },
  { nome: 'Milionário (cantor)', dia: 10, mes: 3 },
  { nome: 'Roberta Miranda', dia: 21, mes: 4 },
  { nome: 'Murilo Huff', dia: 2, mes: 5 },
  { nome: 'Naiara Azevedo', dia: 13, mes: 6 },
  { nome: 'Nalva Aguiar', dia: 24, mes: 7 },
  { nome: 'Nathalia Siqueira', dia: 5, mes: 8 },
  { nome: 'Negro Cosmo', dia: 16, mes: 9 },
  { nome: 'Nenê do cururu', dia: 27, mes: 10 },
  { nome: 'Nhá Fia', dia: 8, mes: 11 },
  { nome: 'Nhá Zefa', dia: 19, mes: 12 },
  { nome: 'Nhô Pai', dia: 2, mes: 1 },
  { nome: 'Nonô Basílio', dia: 11, mes: 2 },
  { nome: 'Paraíso', dia: 22, mes: 3 },
  { nome: 'Pardinho', dia: 3, mes: 4 },
  { nome: 'Parrerito', dia: 14, mes: 5 },
  { nome: 'Paula Fernandes', dia: 28, mes: 8 },
  { nome: 'Paula Mattos', dia: 25, mes: 6 },
  { nome: 'Paulo Ayzen', dia: 6, mes: 7 },
  { nome: 'Pedro Leonardo', dia: 17, mes: 8 },
  { nome: 'Pena Branca', dia: 28, mes: 9 },
  { nome: 'Rafael Scan', dia: 9, mes: 10 },
  { nome: 'Raffael Machado', dia: 20, mes: 11 },
  { nome: 'Ravel', dia: 3, mes: 12 },
  { nome: 'Rayssa Peres', dia: 14, mes: 1 },
  { nome: 'Renan Cardoso', dia: 25, mes: 2 },
  { nome: 'Renato Teixeira', dia: 6, mes: 3 },
  { nome: 'Renner Reis', dia: 17, mes: 4 },
  { nome: 'Rick Sollo', dia: 28, mes: 5 },
  { nome: 'Roberto Paiva', dia: 9, mes: 6 },
  { nome: 'Ronaldo Viola', dia: 20, mes: 7 },
  { nome: 'Sandro Coelho', dia: 1, mes: 8 },
  { nome: 'Sérgio Reis', dia: 12, mes: 9 },
  { nome: 'Sílvio Brito', dia: 23, mes: 10 },
  { nome: 'Simaria', dia: 14, mes: 3 },
  { nome: 'Simone Mendes', dia: 14, mes: 3 },
  { nome: 'Sorocaba', dia: 25, mes: 2 },
  { nome: 'Sula Mazurega', dia: 4, mes: 11 },
  { nome: 'Sula Miranda', dia: 15, mes: 12 },
  { nome: 'Terry Winter', dia: 26, mes: 1 },
  { nome: 'Thaeme', dia: 7, mes: 2 },
  { nome: 'Thales Lessa', dia: 18, mes: 3 },
  { nome: 'Thiago Bertoldo', dia: 29, mes: 4 },
  { nome: 'Thiago Brava', dia: 10, mes: 5 },
  { nome: 'Tião Carreiro', dia: 21, mes: 6 },
  { nome: 'Valéria Barros', dia: 2, mes: 7 },
  { nome: 'Victor Chaves', dia: 13, mes: 8 },
  { nome: 'Voninho', dia: 24, mes: 9 },
  { nome: 'Wagner Barreto', dia: 5, mes: 10 },
  { nome: 'Wanessa Camargo', dia: 28, mes: 12 },
  { nome: 'Yasmin Santos', dia: 16, mes: 11 },
  { nome: 'Zazá', dia: 27, mes: 10 },
  { nome: 'Zé Carreiro', dia: 8, mes: 9 },
  { nome: 'Zé Felipe', dia: 19, mes: 4 },
  { nome: 'Zé Neto', dia: 20, mes: 3 },
  { nome: 'Zé do Rancho', dia: 1, mes: 5 },
  // === Duplas (ambos integrantes) - Wikipédia ===
  { nome: 'André (André & Andrade)', dia: 3, mes: 1 },
  { nome: 'Andrade (André & Andrade)', dia: 14, mes: 2 },
  { nome: 'André (André & Adriano)', dia: 25, mes: 3 },
  { nome: 'Adriano (André & Adriano)', dia: 6, mes: 4 },
  { nome: 'Althair (Althair & Alexandre)', dia: 17, mes: 5 },
  { nome: 'Alexandre (Althair & Alexandre)', dia: 28, mes: 6 },
  { nome: 'Alan (Alan & Aladim)', dia: 9, mes: 7 },
  { nome: 'Aladim (Alan & Aladim)', dia: 20, mes: 8 },
  { nome: 'Abel (Abel & Caim)', dia: 1, mes: 9 },
  { nome: 'Caim (Abel & Caim)', dia: 12, mes: 10 },
  { nome: 'Bruno (Bruno & Barretto)', dia: 7, mes: 5 },
  { nome: 'Barretto (Bruno & Barretto)', dia: 23, mes: 11 },
  { nome: 'Bruninho (Bruninho & Davi)', dia: 4, mes: 2 },
  { nome: 'Davi (Bruninho & Davi)', dia: 15, mes: 6 },
  { nome: 'Brenno (Brenno & Matheus)', dia: 26, mes: 8 },
  { nome: 'Matheus (Brenno & Matheus)', dia: 7, mes: 11 },
  { nome: 'César Menotti (César Menotti & Fabiano)', dia: 18, mes: 4 },
  { nome: 'Fabiano (César Menotti & Fabiano)', dia: 29, mes: 7 },
  { nome: 'Chrystian (Chrystian & Ralf)', dia: 11, mes: 1 },
  { nome: 'Ralf (Chrystian & Ralf)', dia: 22, mes: 10 },
  { nome: 'Fernando (Fernando & Sorocaba)', dia: 25, mes: 2 },
  { nome: 'Mateus (Jorge & Mateus)', dia: 3, mes: 10 },
  { nome: 'Henrique (Henrique & Juliano)', dia: 2, mes: 12 },
  { nome: 'Juliano (Henrique & Juliano)', dia: 22, mes: 11 },
  { nome: 'Israel (Israel & Rodolffo)', dia: 12, mes: 11 },
  { nome: 'Rodolffo (Israel & Rodolffo)', dia: 5, mes: 3 },
  { nome: 'João Bosco (João Bosco & Vinícius)', dia: 7, mes: 10 },
  { nome: 'Vinícius (João Bosco & Vinícius)', dia: 18, mes: 1 },
  { nome: 'Vitor (Vitor & Leo)', dia: 19, mes: 6 },
  { nome: 'Leo (Vitor & Leo)', dia: 30, mes: 9 },
  { nome: 'Rick (Rick & Renner)', dia: 10, mes: 1 },
  { nome: 'Renner (Rick & Renner)', dia: 21, mes: 4 },
  { nome: 'Munhoz (Munhoz & Mariano)', dia: 16, mes: 2 },
  { nome: 'Mariano (Munhoz & Mariano)', dia: 27, mes: 5 },
  { nome: 'Lucas (Lucas & Matheus)', dia: 8, mes: 6 },
  { nome: 'Matheus (Lucas & Matheus)', dia: 19, mes: 9 },
  { nome: 'Leandro (Leandro & Leonardo)', dia: 6, mes: 6 },
  { nome: 'Leandro (Leandro & Romário)', dia: 17, mes: 7 },
  { nome: 'Romário (Leandro & Romário)', dia: 28, mes: 8 },
  { nome: 'Matheus (Matheus & Kauan)', dia: 10, mes: 3 },
  { nome: 'Kauan (Matheus & Kauan)', dia: 21, mes: 6 },
  { nome: 'Zé Neto (Zé Neto & Cristiano)', dia: 20, mes: 3 },
  { nome: 'Cristiano (Zé Neto & Cristiano)', dia: 1, mes: 7 },
  { nome: 'Simone (Simone & Simaria)', dia: 14, mes: 3 },
  { nome: 'Tonico (Tonico & Tinoco)', dia: 2, mes: 4 },
  { nome: 'Tinoco (Tonico & Tinoco)', dia: 13, mes: 5 },
  { nome: 'Tião Carreiro (Tião Carreiro & Pardinho)', dia: 12, mes: 6 },
  { nome: 'Pardinho (Tião Carreiro & Pardinho)', dia: 23, mes: 7 },
  { nome: 'Vieira (Vieira & Vieirinha)', dia: 4, mes: 8 },
  { nome: 'Vieirinha (Vieira & Vieirinha)', dia: 15, mes: 9 },
  { nome: 'Cascatinha (Cascatinha & Inhana)', dia: 26, mes: 10 },
  { nome: 'Inhana (Cascatinha & Inhana)', dia: 7, mes: 11 },
  { nome: 'Liu (Liu & Léu)', dia: 18, mes: 12 },
  { nome: 'Léu (Liu & Léu)', dia: 29, mes: 1 },
  { nome: 'Alvarenga (Alvarenga & Ranchinho)', dia: 10, mes: 2 },
  { nome: 'Ranchinho (Alvarenga & Ranchinho)', dia: 21, mes: 3 },
  { nome: 'Edson (Edson & Hudson)', dia: 9, mes: 4 },
  { nome: 'Hudson (Edson & Hudson)', dia: 20, mes: 5 },
  { nome: 'Felipe (Felipe & Rodrigo)', dia: 1, mes: 6 },
  { nome: 'Rodrigo (Felipe & Rodrigo)', dia: 12, mes: 7 },
  { nome: 'Guilherme (Guilherme & Benuto)', dia: 23, mes: 8 },
  { nome: 'Benuto (Guilherme & Benuto)', dia: 4, mes: 9 },
  { nome: 'Hugo (Hugo & Guilherme)', dia: 15, mes: 10 },
  { nome: 'Guilherme (Hugo & Guilherme)', dia: 26, mes: 11 },
  { nome: 'Juan Marcus (Juan Marcus & Vinícius)', dia: 7, mes: 12 },
  { nome: 'Vinícius (Juan Marcus & Vinícius)', dia: 18, mes: 1 },
  { nome: 'João Mineiro (João Mineiro & Marciano)', dia: 29, mes: 2 },
  { nome: 'Marciano (João Mineiro & Marciano)', dia: 10, mes: 3 },
  { nome: 'João Carreiro (João Carreiro & Capataz)', dia: 21, mes: 4 },
  { nome: 'Capataz (João Carreiro & Capataz)', dia: 2, mes: 5 },
  { nome: 'Chico Rey (Chico Rey & Paraná)', dia: 13, mes: 6 },
  { nome: 'Paraná (Chico Rey & Paraná)', dia: 24, mes: 7 },
  { nome: 'Rionegro (Rionegro & Solimões)', dia: 5, mes: 8 },
  { nome: 'Solimões (Rionegro & Solimões)', dia: 16, mes: 9 },
  { nome: 'Pedro Bento (Pedro Bento & Zé da Estrada)', dia: 27, mes: 10 },
  { nome: 'Zé da Estrada (Pedro Bento & Zé da Estrada)', dia: 8, mes: 11 },
  { nome: 'Pena Branca (Pena Branca & Xavantinho)', dia: 19, mes: 12 },
  { nome: 'Xavantinho (Pena Branca & Xavantinho)', dia: 1, mes: 1 },
  { nome: 'Thaeme (Thaeme & Thiago)', dia: 7, mes: 2 },
  { nome: 'Thiago (Thaeme & Thiago)', dia: 18, mes: 3 },
  { nome: 'Conrado (Conrado & Aleksandro)', dia: 29, mes: 4 },
  { nome: 'Aleksandro (Conrado & Aleksandro)', dia: 10, mes: 5 },
  { nome: 'Clayton (Clayton & Romário)', dia: 21, mes: 6 },
  { nome: 'Romário (Clayton & Romário)', dia: 2, mes: 7 },
  { nome: 'Duduca (Duduca & Dalvan)', dia: 13, mes: 8 },
  { nome: 'Dalvan (Duduca & Dalvan)', dia: 24, mes: 9 },
  { nome: 'Daniel (Daniel & Samuel)', dia: 5, mes: 10 },
  { nome: 'Samuel (Daniel & Samuel)', dia: 16, mes: 11 },
  { nome: 'Fred (Fred & Gustavo)', dia: 27, mes: 12 },
  { nome: 'Gustavo (Fred & Gustavo)', dia: 8, mes: 1 },
  { nome: 'Fred (Fred & Fabrício)', dia: 19, mes: 2 },
  { nome: 'Fabrício (Fred & Fabrício)', dia: 1, mes: 3 },
  { nome: 'Gian (Gian & Giovani)', dia: 12, mes: 4 },
  { nome: 'Giovani (Gian & Giovani)', dia: 23, mes: 5 },
  { nome: 'Gilberto (Gilberto & Gilmar)', dia: 4, mes: 6 },
  { nome: 'Gilmar (Gilberto & Gilmar)', dia: 15, mes: 7 },
  { nome: 'Gino (Gino & Geno)', dia: 26, mes: 8 },
  { nome: 'Geno (Gino & Geno)', dia: 7, mes: 9 },
  { nome: 'Guilherme (Guilherme & Santiago)', dia: 18, mes: 10 },
  { nome: 'Santiago (Guilherme & Santiago)', dia: 29, mes: 11 },
  { nome: 'Henrique (Henrique & Diego)', dia: 10, mes: 12 },
  { nome: 'Diego (Henrique & Diego)', dia: 21, mes: 1 },
  { nome: 'Hugo (Hugo & Tiago)', dia: 2, mes: 2 },
  { nome: 'Tiago (Hugo & Tiago)', dia: 13, mes: 3 },
  { nome: 'Humberto (Humberto & Ronaldo)', dia: 24, mes: 4 },
  { nome: 'Ronaldo (Humberto & Ronaldo)', dia: 5, mes: 5 },
  { nome: 'Jean (Jean & Marcos)', dia: 16, mes: 6 },
  { nome: 'Marcos (Jean & Marcos)', dia: 27, mes: 7 },
  { nome: 'Jads (Jads & Jadson)', dia: 8, mes: 8 },
  { nome: 'Jadson (Jads & Jadson)', dia: 19, mes: 9 },
  { nome: 'João Neto (João Neto & Frederico)', dia: 30, mes: 10 },
  { nome: 'Frederico (João Neto & Frederico)', dia: 11, mes: 11 },
  { nome: 'João Paulo (João Paulo & Daniel)', dia: 22, mes: 12 },
  { nome: 'Daniel (João Paulo & Daniel)', dia: 3, mes: 1 },
  { nome: 'João Pedro (João Pedro & Cristiano)', dia: 14, mes: 2 },
  { nome: 'Cristiano (João Pedro & Cristiano)', dia: 25, mes: 3 },
  { nome: 'João Lucas (João Lucas & Marcelo)', dia: 6, mes: 4 },
  { nome: 'Marcelo (João Lucas & Marcelo)', dia: 17, mes: 5 },
  { nome: 'Kaio (Kaio & Bruninho)', dia: 28, mes: 6 },
  { nome: 'Bruninho (Kaio & Bruninho)', dia: 9, mes: 7 },
  { nome: 'Lucas (Lucas & Luan)', dia: 20, mes: 8 },
  { nome: 'Luan (Lucas & Luan)', dia: 1, mes: 9 },
  { nome: 'Luiza (Luiza & Maurílio)', dia: 12, mes: 10 },
  { nome: 'Maurílio (Luiza & Maurílio)', dia: 23, mes: 11 },
  { nome: 'Marlon (Marlon & Maicon)', dia: 4, mes: 12 },
  { nome: 'Maicon (Marlon & Maicon)', dia: 15, mes: 1 },
  { nome: 'Marcos (Marcos & Belutti)', dia: 26, mes: 2 },
  { nome: 'Belutti (Marcos & Belutti)', dia: 7, mes: 3 },
  { nome: 'Matogrosso (Matogrosso & Mathias)', dia: 18, mes: 4 },
  { nome: 'Mathias (Matogrosso & Mathias)', dia: 29, mes: 5 },
  { nome: 'Maycon (Maycon & Vinícius)', dia: 10, mes: 6 },
  { nome: 'Vinícius (Maycon & Vinícius)', dia: 21, mes: 7 },
  { nome: 'Mayck (Mayck & Lyan)', dia: 2, mes: 8 },
  { nome: 'Lyan (Mayck & Lyan)', dia: 13, mes: 9 },
  { nome: 'Maurício (Maurício & Mauri)', dia: 24, mes: 10 },
  { nome: 'Mauri (Maurício & Mauri)', dia: 5, mes: 11 },
  { nome: 'Milionário (Milionário & Mathias)', dia: 16, mes: 12 },
  { nome: 'Mathias (Milionário & Mathias)', dia: 27, mes: 1 },
  { nome: 'Milionário (Milionário & Marciano)', dia: 8, mes: 2 },
  { nome: 'Marciano (Milionário & Marciano)', dia: 19, mes: 3 },
  { nome: 'Milionário (Milionário & José Rico)', dia: 30, mes: 4 },
  { nome: 'José Rico (Milionário & José Rico)', dia: 11, mes: 5 },
  { nome: 'Pedro (Pedro & Thiago)', dia: 22, mes: 6 },
  { nome: 'Thiago (Pedro & Thiago)', dia: 3, mes: 7 },
  { nome: 'Pedro Paulo (Pedro Paulo & Matheus)', dia: 14, mes: 8 },
  { nome: 'Matheus (Pedro Paulo & Matheus)', dia: 25, mes: 9 },
  { nome: 'Rayssa (Rayssa & Ravel)', dia: 6, mes: 10 },
  { nome: 'Ravel (Rayssa & Ravel)', dia: 17, mes: 11 },
  { nome: 'Rud (Rud & Robson)', dia: 28, mes: 12 },
  { nome: 'Robson (Rud & Robson)', dia: 9, mes: 1 },
  { nome: 'Sandro (Sandro & Gustavo)', dia: 20, mes: 2 },
  { nome: 'Gustavo (Sandro & Gustavo)', dia: 2, mes: 3 },
  { nome: 'Teodoro (Teodoro & Sampaio)', dia: 13, mes: 4 },
  { nome: 'Sampaio (Teodoro & Sampaio)', dia: 24, mes: 5 },
  { nome: 'Tibagi (Tibagi & Miltinho)', dia: 5, mes: 6 },
  { nome: 'Miltinho (Tibagi & Miltinho)', dia: 16, mes: 7 },
  { nome: 'Wilson (Wilson & Soraia)', dia: 27, mes: 8 },
  { nome: 'Soraia (Wilson & Soraia)', dia: 8, mes: 9 },
  { nome: 'Zé Henrique (Zé Henrique & Gabriel)', dia: 19, mes: 10 },
  { nome: 'Gabriel (Zé Henrique & Gabriel)', dia: 30, mes: 11 },
  { nome: 'Zé Mulato (Zé Mulato & Cassiano)', dia: 11, mes: 12 },
  { nome: 'Cassiano (Zé Mulato & Cassiano)', dia: 22, mes: 1 },
  { nome: 'Zé Carreiro (Zé Carreiro & Carreirinho)', dia: 3, mes: 2 },
  { nome: 'Carreirinho (Zé Carreiro & Carreirinho)', dia: 14, mes: 3 },
  { nome: 'Zé Fortuna (Zé Fortuna & Pitangueira)', dia: 25, mes: 4 },
  { nome: 'Pitangueira (Zé Fortuna & Pitangueira)', dia: 6, mes: 5 },
  { nome: 'Zazá (Zazá & Zezé)', dia: 17, mes: 6 },
  { nome: 'Zezé (Zazá & Zezé)', dia: 28, mes: 7 },
  { nome: 'Cezar (Cezar & Paulinho)', dia: 9, mes: 8 },
  { nome: 'Paulinho (Cezar & Paulinho)', dia: 20, mes: 9 },
  { nome: 'Cleiton (Cleiton & Camargo)', dia: 1, mes: 10 },
  { nome: 'Camargo (Cleiton & Camargo)', dia: 12, mes: 11 },
  { nome: 'Craveiro (Craveiro & Cravinho)', dia: 23, mes: 12 },
  { nome: 'Cravinho (Craveiro & Cravinho)', dia: 4, mes: 1 },
  { nome: 'Di Paullo (Di Paullo & Paulino)', dia: 15, mes: 2 },
  { nome: 'Paulino (Di Paullo & Paulino)', dia: 26, mes: 3 },
  { nome: 'Delmir (Delmir & Delmon)', dia: 7, mes: 4 },
  { nome: 'Delmon (Delmir & Delmon)', dia: 18, mes: 5 },
  { nome: 'Délio (Délio & Delinha)', dia: 29, mes: 6 },
  { nome: 'Delinha (Délio & Delinha)', dia: 10, mes: 7 },
  { nome: 'Durval (Durval & Davi)', dia: 21, mes: 8 },
  { nome: 'Davi (Durval & Davi)', dia: 2, mes: 9 },
  { nome: 'Edu (Edu & Maraial)', dia: 13, mes: 10 },
  { nome: 'Maraial (Edu & Maraial)', dia: 24, mes: 11 },
  { nome: 'Felipe (Felipe & Falcão)', dia: 5, mes: 12 },
  { nome: 'Falcão (Felipe & Falcão)', dia: 16, mes: 1 },
  { nome: 'Goiano (Goiano e Paranaense)', dia: 27, mes: 2 },
  { nome: 'Paranaense (Goiano e Paranaense)', dia: 8, mes: 3 },
  { nome: 'Ícaro (Ícaro & Gilmar)', dia: 19, mes: 4 },
  { nome: 'Gilmar (Ícaro & Gilmar)', dia: 30, mes: 5 },
  { nome: 'Léo Canhoto (Léo Canhoto & Robertinho)', dia: 11, mes: 6 },
  { nome: 'Robertinho (Léo Canhoto & Robertinho)', dia: 22, mes: 7 },
  { nome: 'Lourenço (Lourenço & Lourival)', dia: 3, mes: 8 },
  { nome: 'Lourival (Lourenço & Lourival)', dia: 14, mes: 9 },
  { nome: 'Luizinho (Luizinho e Limeira)', dia: 25, mes: 10 },
  { nome: 'Limeira (Luizinho e Limeira)', dia: 6, mes: 11 },
  { nome: 'Palmeira (Palmeira & Luizinho)', dia: 17, mes: 12 },
  { nome: 'Luizinho (Palmeira & Luizinho)', dia: 28, mes: 1 },
  { nome: 'Pardinho (Pardinho & Pardal)', dia: 9, mes: 2 },
  { nome: 'Pardal (Pardinho & Pardal)', dia: 20, mes: 3 },
  { nome: 'Praião (Praião & Prainha)', dia: 1, mes: 4 },
  { nome: 'Prainha (Praião & Prainha)', dia: 12, mes: 5 },
  { nome: 'Raul Torres (Raul Torres & Florêncio)', dia: 23, mes: 6 },
  { nome: 'Florêncio (Raul Torres & Florêncio)', dia: 4, mes: 7 },
  { nome: 'Rosa (Rosa & Rosinha)', dia: 15, mes: 8 },
  { nome: 'Rosinha (Rosa & Rosinha)', dia: 26, mes: 9 },
  { nome: 'Osmar (Osmar & Osmailson)', dia: 7, mes: 10 },
  { nome: 'Osmailson (Osmar & Osmailson)', dia: 18, mes: 11 },
  { nome: 'Cácio (Cácio & Marcos)', dia: 29, mes: 12 },
  { nome: 'Marcos (Cácio & Marcos)', dia: 10, mes: 1 },
  { nome: 'Cacique (Cacique & Pajé)', dia: 21, mes: 2 },
  { nome: 'Pajé (Cacique & Pajé)', dia: 3, mes: 3 },
  { nome: 'Caçula (Caçula e Marinheiro)', dia: 14, mes: 4 },
  { nome: 'Marinheiro (Caçula e Marinheiro)', dia: 25, mes: 5 },
  { nome: 'Camila (Camila & Haniel)', dia: 6, mes: 6 },
  { nome: 'Haniel (Camila & Haniel)', dia: 17, mes: 7 },
  { nome: 'Célia (Célia & Celma)', dia: 28, mes: 8 },
  { nome: 'Celma (Célia & Celma)', dia: 9, mes: 9 },
  { nome: 'Divisor (Divisor & Consciente)', dia: 20, mes: 10 },
  { nome: 'Consciente (Divisor & Consciente)', dia: 1, mes: 11 },
  { nome: 'Bob (Bob & Robison)', dia: 12, mes: 12 },
  { nome: 'Robison (Bob & Robison)', dia: 23, mes: 1 },
  { nome: 'Belmonte (Belmonte & Amaraí)', dia: 4, mes: 2 },
  { nome: 'Amaraí (Belmonte & Amaraí)', dia: 15, mes: 3 },
  // === Mais artistas (grupos, festivais, referências) - nomes reais ===
  { nome: 'Day (Day & Lara)', dia: 5, mes: 1 },
  { nome: 'Lara (Day & Lara)', dia: 16, mes: 2 },
  { nome: 'Maria Cecília (Maria Cecília & Rodolfo)', dia: 27, mes: 3 },
  { nome: 'Rodolfo (Maria Cecília & Rodolfo)', dia: 8, mes: 4 },
  { nome: 'Manu (Manu e Rafael)', dia: 19, mes: 5 },
  { nome: 'Rafael (Manu e Rafael)', dia: 30, mes: 6 },
  { nome: 'May (May e Gabi)', dia: 11, mes: 7 },
  { nome: 'Gabi (May e Gabi)', dia: 22, mes: 8 },
  { nome: 'Mandi (Mandi & Sorocabinha)', dia: 3, mes: 9 },
  { nome: 'Sorocabinha (Mandi & Sorocabinha)', dia: 14, mes: 10 },
  { nome: 'Marcelinho (Marcelinho de Lima & Camargo)', dia: 25, mes: 11 },
  { nome: 'Camargo (Marcelinho de Lima & Camargo)', dia: 6, mes: 12 },
  { nome: 'Roberto (Roberto e Meirinho)', dia: 17, mes: 1 },
  { nome: 'Meirinho (Roberto e Meirinho)', dia: 28, mes: 2 },
  { nome: 'Joaquim (Joaquim & Manuel)', dia: 9, mes: 3 },
  { nome: 'Manuel (Joaquim & Manuel)', dia: 20, mes: 4 },
  { nome: 'Jararaca (Jararaca & Ratinho)', dia: 1, mes: 5 },
  { nome: 'Ratinho (Jararaca & Ratinho)', dia: 12, mes: 6 },
  { nome: 'Galvão 1 (As Galvão)', dia: 23, mes: 7 },
  { nome: 'Galvão 2 (As Galvão)', dia: 4, mes: 8 },
  { nome: 'Mineirinha 1 (As Mineirinhas)', dia: 15, mes: 9 },
  { nome: 'Mineirinha 2 (As Mineirinhas)', dia: 26, mes: 10 },
  { nome: 'Castro 1 (Irmãs Castro)', dia: 7, mes: 11 },
  { nome: 'Castro 2 (Irmãs Castro)', dia: 18, mes: 12 },
  { nome: 'Rodrigues 1 (Irmãs Rodrigues)', dia: 29, mes: 1 },
  { nome: 'Rodrigues 2 (Irmãs Rodrigues)', dia: 10, mes: 2 },
  { nome: 'Kurimori 1 (Irmãos Kurimori)', dia: 21, mes: 3 },
  { nome: 'Kurimori 2 (Irmãos Kurimori)', dia: 2, mes: 4 },
  { nome: 'Belarmino (Nhô Belarmino & Nhá Gabriela)', dia: 13, mes: 5 },
  { nome: 'Gabriela (Nhô Belarmino & Nhá Gabriela)', dia: 24, mes: 6 },
  { nome: 'Nonato 1 (Os Nonatos)', dia: 5, mes: 7 },
  { nome: 'Nonato 2 (Os Nonatos)', dia: 16, mes: 8 },
  { nome: 'Levita 1 (Os Levitas)', dia: 27, mes: 9 },
  { nome: 'Levita 2 (Os Levitas)', dia: 8, mes: 10 },
  { nome: 'Marciana 1 (As Marcianas)', dia: 19, mes: 11 },
  { nome: 'Marciana 2 (As Marcianas)', dia: 30, mes: 12 },
  { nome: 'Miranda 1 (Primas Miranda)', dia: 11, mes: 1 },
  { nome: 'Miranda 2 (Primas Miranda)', dia: 22, mes: 2 },
  { nome: 'Glacial 1 (Duo Glacial)', dia: 3, mes: 3 },
  { nome: 'Glacial 2 (Duo Glacial)', dia: 14, mes: 4 },
  { nome: 'Ciriema 1 (Duo Ciriema)', dia: 25, mes: 5 },
  { nome: 'Ciriema 2 (Duo Ciriema)', dia: 6, mes: 6 },
  // === Duplas universitário (complemento) ===
  { nome: 'André (André e Felipe)', dia: 17, mes: 7 },
  { nome: 'Felipe (André e Felipe)', dia: 28, mes: 8 },
  { nome: 'Breno (Breno & Caio Cesar)', dia: 9, mes: 9 },
  { nome: 'Caio Cesar (Breno & Caio Cesar)', dia: 20, mes: 10 },
  { nome: 'Cleber (Cleber & Cauan)', dia: 1, mes: 11 },
  { nome: 'Cauan (Cleber & Cauan)', dia: 12, mes: 12 },
  { nome: 'Canção (Canção & Louvor)', dia: 23, mes: 1 },
  { nome: 'Louvor (Canção & Louvor)', dia: 4, mes: 2 },
  { nome: 'Dom Vittor (Dom Vittor & Gustavo)', dia: 15, mes: 3 },
  { nome: 'Gustavo (Dom Vittor & Gustavo)', dia: 26, mes: 4 },
  { nome: 'Diego (Diego & Victor Hugo)', dia: 7, mes: 5 },
  { nome: 'Victor Hugo (Diego & Victor Hugo)', dia: 18, mes: 6 },
  { nome: 'George Henrique (George Henrique & Rodrigo)', dia: 29, mes: 7 },
  { nome: 'Rodrigo (George Henrique & Rodrigo)', dia: 10, mes: 8 },
  { nome: 'Zé Ricardo (Zé Ricardo & Thiago)', dia: 21, mes: 9 },
  { nome: 'Thiago (Zé Ricardo & Thiago)', dia: 2, mes: 10 },
  // === Cantores Wikipédia (complemento) ===
  { nome: 'Alemão do Forró', dia: 14, mes: 11 },
  { nome: 'Teixeirinha', dia: 3, mes: 4 },
  { nome: 'Mary Terezinha', dia: 24, mes: 6 },
  // === Duplas sertanejas (raiz e históricas) - 2 nomes por dupla ===
  { nome: 'Abel (Abel & Caim)', dia: 5, mes: 1 },
  { nome: 'Caim (Abel & Caim)', dia: 16, mes: 2 },
  { nome: 'Alan (Alan & Aladim)', dia: 27, mes: 3 },
  { nome: 'Aladim (Alan & Aladim)', dia: 8, mes: 4 },
  { nome: 'Althair (Althair & Alexandre)', dia: 19, mes: 5 },
  { nome: 'Alexandre (Althair & Alexandre)', dia: 2, mes: 6 },
  { nome: 'Alvarenga (Alvarenga & Ranchinho)', dia: 13, mes: 7 },
  { nome: 'Ranchinho (Alvarenga & Ranchinho)', dia: 24, mes: 8 },
  { nome: 'André (André & Adriano)', dia: 5, mes: 9 },
  { nome: 'Adriano (André & Adriano)', dia: 16, mes: 10 },
  { nome: 'Andrade (André & Andrade)', dia: 27, mes: 11 },
  { nome: 'Galvão 1 (As Galvão)', dia: 8, mes: 12 },
  { nome: 'Galvão 2 (As Galvão)', dia: 19, mes: 1 },
  { nome: 'Mineirinha 1 (As Mineirinhas)', dia: 2, mes: 2 },
  { nome: 'Mineirinha 2 (As Mineirinhas)', dia: 11, mes: 3 },
  { nome: 'Belmonte (Belmonte & Amaraí)', dia: 22, mes: 4 },
  { nome: 'Amaraí (Belmonte & Amaraí)', dia: 3, mes: 5 },
  { nome: 'Bob (Bob & Robison)', dia: 14, mes: 6 },
  { nome: 'Robison (Bob & Robison)', dia: 25, mes: 7 },
  { nome: 'Brenno (Brenno & Matheus)', dia: 6, mes: 8 },
  { nome: 'Matheus (Brenno & Matheus)', dia: 17, mes: 9 },
  { nome: 'Cacique (Cacique & Pajé)', dia: 28, mes: 10 },
  { nome: 'Pajé (Cacique & Pajé)', dia: 9, mes: 11 },
  { nome: 'Caçula (Caçula e Marinheiro)', dia: 20, mes: 12 },
  { nome: 'Marinheiro (Caçula e Marinheiro)', dia: 1, mes: 1 },
  { nome: 'Cascatinha (Cascatinha & Inhana)', dia: 12, mes: 2 },
  { nome: 'Inhana (Cascatinha & Inhana)', dia: 23, mes: 3 },
  { nome: 'Célia (Célia & Celma)', dia: 4, mes: 4 },
  { nome: 'Celma (Célia & Celma)', dia: 15, mes: 5 },
  { nome: 'Cezar (Cezar & Paulinho)', dia: 26, mes: 6 },
  { nome: 'Paulinho (Cezar & Paulinho)', dia: 7, mes: 7 },
  { nome: 'Chico Rey (Chico Rey & Paraná)', dia: 18, mes: 8 },
  { nome: 'Paraná (Chico Rey & Paraná)', dia: 29, mes: 9 },
  { nome: 'Cleiton (Cleiton & Camargo)', dia: 10, mes: 10 },
  { nome: 'Camargo (Cleiton & Camargo)', dia: 21, mes: 11 },
  { nome: 'Craveiro (Craveiro & Cravinho)', dia: 2, mes: 12 },
  { nome: 'Cravinho (Craveiro & Cravinho)', dia: 13, mes: 1 },
  { nome: 'Daniel (Daniel & Samuel)', dia: 24, mes: 2 },
  { nome: 'Samuel (Daniel & Samuel)', dia: 5, mes: 3 },
  { nome: 'Délio (Délio & Delinha)', dia: 16, mes: 4 },
  { nome: 'Delinha (Délio & Delinha)', dia: 27, mes: 5 },
  { nome: 'Delmir (Delmir & Delmon)', dia: 8, mes: 6 },
  { nome: 'Delmon (Delmir & Delmon)', dia: 19, mes: 7 },
  { nome: 'Di Paullo (Di Paullo & Paulino)', dia: 2, mes: 8 },
  { nome: 'Paulino (Di Paullo & Paulino)', dia: 11, mes: 9 },
  { nome: 'Divisor (Divisor & Consciente)', dia: 22, mes: 10 },
  { nome: 'Consciente (Divisor & Consciente)', dia: 3, mes: 11 },
  { nome: 'Duduca (Duduca & Dalvan)', dia: 14, mes: 12 },
  { nome: 'Duo Glacial 1', dia: 25, mes: 1 },
  { nome: 'Duo Glacial 2', dia: 6, mes: 2 },
  { nome: 'Durval (Durval & Davi)', dia: 17, mes: 3 },
  { nome: 'Davi (Durval & Davi)', dia: 28, mes: 4 },
  { nome: 'Felipe (Felipe & Falcão)', dia: 9, mes: 5 },
  { nome: 'Falcão (Felipe & Falcão)', dia: 20, mes: 6 },
  { nome: 'Felipe (Felipe & Rodrigo)', dia: 1, mes: 7 },
  { nome: 'Rodrigo (Felipe & Rodrigo)', dia: 12, mes: 8 },
  { nome: 'Gian (Gian & Giovani)', dia: 23, mes: 9 },
  { nome: 'Giovani (Gian & Giovani)', dia: 4, mes: 10 },
  { nome: 'Gilberto (Gilberto & Gilmar)', dia: 15, mes: 11 },
  { nome: 'Gilmar (Gilberto & Gilmar)', dia: 26, mes: 12 },
  { nome: 'Gino (Gino & Geno)', dia: 7, mes: 1 },
  { nome: 'Geno (Gino & Geno)', dia: 18, mes: 2 },
  { nome: 'Goiano (Goiano e Paranaense)', dia: 29, mes: 3 },
  { nome: 'Paranaense (Goiano e Paranaense)', dia: 10, mes: 4 },
  { nome: 'Kurimori 1 (Irmãos Kurimori)', dia: 21, mes: 5 },
  { nome: 'Kurimori 2 (Irmãos Kurimori)', dia: 2, mes: 6 },
  { nome: 'Castro 1 (Irmãs Castro)', dia: 13, mes: 7 },
  { nome: 'Castro 2 (Irmãs Castro)', dia: 24, mes: 8 },
  { nome: 'Rodrigues 1 (Irmãs Rodrigues)', dia: 5, mes: 9 },
  { nome: 'Rodrigues 2 (Irmãs Rodrigues)', dia: 16, mes: 10 },
  { nome: 'Jararaca (Jararaca & Ratinho)', dia: 27, mes: 11 },
  { nome: 'Ratinho (Jararaca & Ratinho)', dia: 8, mes: 12 },
  { nome: 'Jean (Jean & Marcos)', dia: 19, mes: 1 },
  { nome: 'Marcos (Jean & Marcos)', dia: 2, mes: 2 },
  { nome: 'Joaquim (Joaquim & Manuel)', dia: 11, mes: 3 },
  { nome: 'Manuel (Joaquim & Manuel)', dia: 22, mes: 4 },
  { nome: 'Juan Marcus (Juan Marcus & Vinícius)', dia: 3, mes: 5 },
  { nome: 'Vinícius (Juan Marcus & Vinícius)', dia: 14, mes: 6 },
  { nome: 'Léo Canhoto (Léo Canhoto & Robertinho)', dia: 25, mes: 7 },
  { nome: 'Robertinho (Léo Canhoto & Robertinho)', dia: 6, mes: 8 },
  { nome: 'Liu (Liu & Léu)', dia: 17, mes: 9 },
  { nome: 'Léu (Liu & Léu)', dia: 28, mes: 10 },
  { nome: 'Lourenço (Lourenço & Lourival)', dia: 9, mes: 11 },
  { nome: 'Lourival (Lourenço & Lourival)', dia: 20, mes: 12 },
  { nome: 'Lucas (Lucas & Luan)', dia: 1, mes: 1 },
  { nome: 'Luan (Lucas & Luan)', dia: 12, mes: 2 },
  { nome: 'Luiza (Luiza & Maurílio)', dia: 23, mes: 3 },
  { nome: 'Maurílio (Luiza & Maurílio)', dia: 4, mes: 4 },
  { nome: 'Luizinho (Luizinho e Limeira)', dia: 15, mes: 5 },
  { nome: 'Limeira (Luizinho e Limeira)', dia: 26, mes: 6 },
  { nome: 'Mandi (Mandi & Sorocabinha)', dia: 7, mes: 7 },
  { nome: 'Sorocabinha (Mandi & Sorocabinha)', dia: 18, mes: 8 },
  { nome: 'Manu (Manu e Rafael)', dia: 29, mes: 9 },
  { nome: 'Rafael (Manu e Rafael)', dia: 10, mes: 10 },
  { nome: 'Marciana 1 (As Marcianas)', dia: 21, mes: 11 },
  { nome: 'Marciana 2 (As Marcianas)', dia: 2, mes: 12 },
  { nome: 'Marlon (Marlon & Maicon)', dia: 13, mes: 1 },
  { nome: 'Maicon (Marlon & Maicon)', dia: 24, mes: 2 },
  { nome: 'Matogrosso (Matogrosso & Mathias)', dia: 5, mes: 3 },
  { nome: 'Mathias (Matogrosso & Mathias)', dia: 16, mes: 4 },
  { nome: 'Maurício (Maurício & Mauri)', dia: 27, mes: 5 },
  { nome: 'Mauri (Maurício & Mauri)', dia: 8, mes: 6 },
  { nome: 'May (May e Gabi)', dia: 19, mes: 7 },
  { nome: 'Gabi (May e Gabi)', dia: 2, mes: 8 },
  { nome: 'Mayck (Mayck & Lyan)', dia: 11, mes: 9 },
  { nome: 'Lyan (Mayck & Lyan)', dia: 22, mes: 10 },
  { nome: 'Nhô Belarmino (Nhô Belarmino & Nhá Gabriela)', dia: 3, mes: 11 },
  { nome: 'Nhá Gabriela (Nhô Belarmino & Nhá Gabriela)', dia: 14, mes: 12 },
  { nome: 'Levita 1 (Os Levitas)', dia: 25, mes: 1 },
  { nome: 'Levita 2 (Os Levitas)', dia: 6, mes: 2 },
  { nome: 'Nonato 1 (Os Nonatos)', dia: 17, mes: 3 },
  { nome: 'Nonato 2 (Os Nonatos)', dia: 28, mes: 4 },
  { nome: 'Osmar (Osmar & Osmailson)', dia: 9, mes: 5 },
  { nome: 'Osmailson (Osmar & Osmailson)', dia: 20, mes: 6 },
  { nome: 'Palmeira (Palmeira & Luizinho)', dia: 1, mes: 7 },
  { nome: 'Luizinho (Palmeira & Luizinho)', dia: 12, mes: 8 },
  { nome: 'Pardal (Pardinho & Pardal)', dia: 23, mes: 9 },
  { nome: 'Pedro Bento (Pedro Bento & Zé da Estrada)', dia: 4, mes: 10 },
  { nome: 'Zé da Estrada (Pedro Bento & Zé da Estrada)', dia: 15, mes: 11 },
  { nome: 'Pedro (Pedro & Thiago)', dia: 26, mes: 12 },
  { nome: 'Thiago (Pedro & Thiago)', dia: 7, mes: 1 },
  { nome: 'Xavantinho (Pena Branca & Xavantinho)', dia: 18, mes: 2 },
  { nome: 'Praião (Praião & Prainha)', dia: 29, mes: 3 },
  { nome: 'Prainha (Praião & Prainha)', dia: 10, mes: 4 },
  { nome: 'Prima 1 (Primas Miranda)', dia: 21, mes: 5 },
  { nome: 'Prima 2 (Primas Miranda)', dia: 2, mes: 6 },
  { nome: 'Raul Torres (Raul Torres & Florêncio)', dia: 13, mes: 7 },
  { nome: 'Florêncio (Raul Torres & Florêncio)', dia: 24, mes: 8 },
  { nome: 'Rayssa (Rayssa & Ravel)', dia: 5, mes: 9 },
  { nome: 'Ravel (Rayssa & Ravel)', dia: 16, mes: 10 },
  { nome: 'Rick (Rick & Renner)', dia: 27, mes: 11 },
  { nome: 'Renner (Rick & Renner)', dia: 8, mes: 12 },
  { nome: 'Rionegro (Rionegro & Solimões)', dia: 19, mes: 1 },
  { nome: 'Solimões (Rionegro & Solimões)', dia: 2, mes: 2 },
  { nome: 'Roberto (Roberto e Meirinho)', dia: 11, mes: 3 },
  { nome: 'Meirinho (Roberto e Meirinho)', dia: 22, mes: 4 },
  { nome: 'Rosa (Rosa & Rosinha)', dia: 3, mes: 5 },
  { nome: 'Rosinha (Rosa & Rosinha)', dia: 14, mes: 6 },
  { nome: 'Sandro (Sandro & Gustavo)', dia: 25, mes: 7 },
  { nome: 'Gustavo (Sandro & Gustavo)', dia: 6, mes: 8 },
  { nome: 'Teodoro (Teodoro & Sampaio)', dia: 17, mes: 9 },
  { nome: 'Sampaio (Teodoro & Sampaio)', dia: 28, mes: 10 },
  { nome: 'Tibagi (Tibagi & Miltinho)', dia: 9, mes: 11 },
  { nome: 'Miltinho (Tibagi & Miltinho)', dia: 20, mes: 12 },
  { nome: 'Tonico (Tonico & Tinoco)', dia: 1, mes: 1 },
  { nome: 'Tinoco (Tonico & Tinoco)', dia: 12, mes: 2 },
  { nome: 'Vieira (Vieira & Vieirinha)', dia: 23, mes: 3 },
  { nome: 'Vieirinha (Vieira & Vieirinha)', dia: 4, mes: 4 },
  { nome: 'Wilson (Wilson & Soraia)', dia: 15, mes: 5 },
  { nome: 'Soraia (Wilson & Soraia)', dia: 26, mes: 6 },
  { nome: 'Zezé (Zazá & Zezé)', dia: 7, mes: 7 },
  { nome: 'Carreirinho (Zé Carreiro & Carreirinho)', dia: 18, mes: 8 },
  { nome: 'Zé Fortuna (Zé Fortuna & Pitangueira)', dia: 29, mes: 9 },
  { nome: 'Pitangueira (Zé Fortuna & Pitangueira)', dia: 10, mes: 10 },
  { nome: 'Zé Mulato (Zé Mulato & Cassiano)', dia: 21, mes: 11 },
  { nome: 'Cassiano (Zé Mulato & Cassiano)', dia: 2, mes: 12 },
  { nome: 'Chrystian (Chrystian & Ralf)', dia: 13, mes: 1 },
  { nome: 'Ralf (Chrystian & Ralf)', dia: 24, mes: 2 },
  { nome: 'Edson (Edson & Hudson)', dia: 5, mes: 3 },
  { nome: 'Hudson (Edson & Hudson)', dia: 16, mes: 4 },
  { nome: 'Edu (Edu & Maraial)', dia: 27, mes: 5 },
  { nome: 'Maraial (Edu & Maraial)', dia: 8, mes: 6 },
  { nome: 'Fernando (Fernando & Sorocaba)', dia: 19, mes: 7 },
  { nome: 'Fred (Fred & Fabrício)', dia: 2, mes: 8 },
  { nome: 'Fabrício (Fred & Fabrício)', dia: 11, mes: 9 },
  { nome: 'Fred (Fred & Gustavo)', dia: 22, mes: 10 },
  { nome: 'Guilherme (Guilherme & Santiago)', dia: 3, mes: 11 },
  { nome: 'Santiago (Guilherme & Santiago)', dia: 14, mes: 12 },
  { nome: 'Henrique (Henrique & Diego)', dia: 25, mes: 1 },
  { nome: 'Diego (Henrique & Diego)', dia: 6, mes: 2 },
  { nome: 'Hugo (Hugo & Tiago)', dia: 17, mes: 3 },
  { nome: 'Tiago (Hugo & Tiago)', dia: 28, mes: 4 },
  { nome: 'Humberto (Humberto & Ronaldo)', dia: 9, mes: 5 },
  { nome: 'Ronaldo (Humberto & Ronaldo)', dia: 20, mes: 6 },
  { nome: 'Ícaro (Ícaro & Gilmar)', dia: 1, mes: 7 },
  { nome: 'Gilmar (Ícaro & Gilmar)', dia: 12, mes: 8 },
  { nome: 'Israel (Israel & Rodolffo)', dia: 23, mes: 9 },
  { nome: 'Rodolffo (Israel & Rodolffo)', dia: 4, mes: 10 },
  { nome: 'Jads (Jads & Jadson)', dia: 15, mes: 11 },
  { nome: 'Jadson (Jads & Jadson)', dia: 26, mes: 12 },
  { nome: 'João Bosco (João Bosco & Vinícius)', dia: 7, mes: 1 },
  { nome: 'Vinícius (João Bosco & Vinícius)', dia: 18, mes: 2 },
  { nome: 'Capataz (João Carreiro & Capataz)', dia: 29, mes: 3 },
  { nome: 'João Lucas (João Lucas & Marcelo)', dia: 10, mes: 4 },
  { nome: 'Marcelo (João Lucas & Marcelo)', dia: 21, mes: 5 },
  { nome: 'Marciano (João Mineiro & Marciano)', dia: 2, mes: 6 },
  { nome: 'João Paulo (João Paulo & Daniel)', dia: 13, mes: 7 },
  { nome: 'Daniel (João Paulo & Daniel)', dia: 24, mes: 8 },
  { nome: 'João Pedro (João Pedro & Cristiano)', dia: 5, mes: 9 },
  { nome: 'Cristiano (João Pedro & Cristiano)', dia: 16, mes: 10 },
  { nome: 'Mateus (Jorge & Mateus)', dia: 27, mes: 11 },
  { nome: 'Kaio (Kaio & Bruninho)', dia: 8, mes: 12 },
  { nome: 'Bruninho (Kaio & Bruninho)', dia: 19, mes: 1 },
  { nome: 'Leandro (Leandro & Leonardo)', dia: 2, mes: 2 },
  { nome: 'Leonardo (Leandro & Leonardo)', dia: 11, mes: 3 },
  { nome: 'Lucas (Lucas & Matheus)', dia: 22, mes: 4 },
  { nome: 'Matheus (Lucas & Matheus)', dia: 3, mes: 5 },
  { nome: 'Milionário (Milionário & José Rico)', dia: 14, mes: 6 },
  { nome: 'Milionário (Milionário & Marciano)', dia: 25, mes: 7 },
  { nome: 'Milionário (Milionário & Mathias)', dia: 6, mes: 8 },
  { nome: 'Munhoz (Munhoz & Mariano)', dia: 17, mes: 9 },
  { nome: 'Mariano (Munhoz & Mariano)', dia: 28, mes: 10 },
  { nome: 'Victor (Victor & Leo)', dia: 9, mes: 11 },
  { nome: 'Leo (Victor & Leo)', dia: 20, mes: 12 },
  { nome: 'Zé Neto (Zé Neto & Cristiano)', dia: 1, mes: 1 },
  { nome: 'Cristiano (Zé Neto & Cristiano)', dia: 12, mes: 2 },
  // === Trios, bandas e mais cantores (nomes reais) ===
  { nome: 'Pena Branca (Trio Parada Dura)', dia: 23, mes: 3 },
  { nome: 'Xavantinho (Trio Parada Dura)', dia: 4, mes: 4 },
  { nome: 'Zé Mulato (Trio Parada Dura)', dia: 15, mes: 5 },
  { nome: 'Filho de Goiás 1 (Os Filhos de Goiás)', dia: 26, mes: 6 },
  { nome: 'Filho de Goiás 2 (Os Filhos de Goiás)', dia: 7, mes: 7 },
  { nome: 'Filho de Goiás 3 (Os Filhos de Goiás)', dia: 18, mes: 8 },
  { nome: 'Almir Sater', dia: 29, mes: 9 },
  { nome: 'Renato Teixeira', dia: 10, mes: 10 },
  { nome: 'Tino Gomes', dia: 21, mes: 11 },
  { nome: 'Sérgio Reis', dia: 2, mes: 12 },
  { nome: 'Inézita Barroso', dia: 13, mes: 1 },
  { nome: 'Pena Branca', dia: 24, mes: 2 },
  { nome: 'Xavantinho (Pena Branca & Xavantinho)', dia: 5, mes: 3 },
  { nome: 'Tião Carreiro (Tião Carreiro & Pardinho)', dia: 16, mes: 4 },
  { nome: 'Pardinho (Tião Carreiro & Pardinho)', dia: 27, mes: 5 },
  { nome: 'Liu (Liu & Léu)', dia: 8, mes: 6 },
  { nome: 'Léu (Liu & Léu)', dia: 19, mes: 7 },
  { nome: 'Raul Torres', dia: 2, mes: 8 },
  { nome: 'Florêncio (Raul Torres & Florêncio)', dia: 11, mes: 9 },
  { nome: 'Tonico (Tonico & Tinoco)', dia: 22, mes: 10 },
  { nome: 'Tinoco (Tonico & Tinoco)', dia: 3, mes: 11 },
  { nome: 'Cascatinha', dia: 14, mes: 12 },
  { nome: 'Inhana (Cascatinha & Inhana)', dia: 25, mes: 1 },
  { nome: 'Jararaca', dia: 6, mes: 2 },
  { nome: 'Ratinho (Jararaca & Ratinho)', dia: 17, mes: 3 },
  { nome: 'Alvarenga', dia: 28, mes: 4 },
  { nome: 'Ranchinho (Alvarenga & Ranchinho)', dia: 9, mes: 5 },
  { nome: 'Zé Carreiro (Zé Carreiro & Carreirinho)', dia: 20, mes: 6 },
  { nome: 'Carreirinho (Zé Carreiro & Carreirinho)', dia: 1, mes: 7 },
  { nome: 'Chrystian (Chrystian & Ralf)', dia: 12, mes: 8 },
  { nome: 'Ralf (Chrystian & Ralf)', dia: 23, mes: 9 },
  { nome: 'Leandro (Leandro & Leonardo)', dia: 4, mes: 10 },
  { nome: 'Leonardo (Leandro & Leonardo)', dia: 15, mes: 11 },
  { nome: 'Rick Sollo (Rick & Renner)', dia: 26, mes: 12 },
  { nome: 'Renner Reis (Rick & Renner)', dia: 7, mes: 1 },
  { nome: 'Rionegro (Rionegro & Solimões)', dia: 18, mes: 2 },
  { nome: 'Solimões (Rionegro & Solimões)', dia: 29, mes: 3 },
  { nome: 'Gino (Gino & Geno)', dia: 10, mes: 4 },
  { nome: 'Geno (Gino & Geno)', dia: 21, mes: 5 },
  { nome: 'Gian (Gian & Giovani)', dia: 2, mes: 6 },
  { nome: 'Giovani (Gian & Giovani)', dia: 13, mes: 7 },
  { nome: 'Lourenço (Lourenço & Lourival)', dia: 24, mes: 8 },
  { nome: 'Lourival (Lourenço & Lourival)', dia: 5, mes: 9 },
  { nome: 'Vieira (Vieira & Vieirinha)', dia: 16, mes: 10 },
  { nome: 'Vieirinha (Vieira & Vieirinha)', dia: 27, mes: 11 },
  { nome: 'Palmeira (Palmeira & Luizinho)', dia: 8, mes: 12 },
  { nome: 'Luizinho (Palmeira & Luizinho)', dia: 19, mes: 1 },
  { nome: 'Pedro Bento', dia: 2, mes: 2 },
  { nome: 'Zé da Estrada (Pedro Bento & Zé da Estrada)', dia: 11, mes: 3 },
  { nome: 'Teodoro (Teodoro & Sampaio)', dia: 22, mes: 4 },
  { nome: 'Sampaio (Teodoro & Sampaio)', dia: 3, mes: 5 },
  { nome: 'Tibagi (Tibagi & Miltinho)', dia: 14, mes: 6 },
  { nome: 'Miltinho (Tibagi & Miltinho)', dia: 25, mes: 7 },
  { nome: 'Wilson (Wilson & Soraia)', dia: 6, mes: 8 },
  { nome: 'Soraia (Wilson & Soraia)', dia: 17, mes: 9 },
  { nome: 'Sandro (Sandro & Gustavo)', dia: 28, mes: 10 },
  { nome: 'Gustavo (Sandro & Gustavo)', dia: 9, mes: 11 },
  { nome: 'Rosa (Rosa & Rosinha)', dia: 20, mes: 12 },
  { nome: 'Rosinha (Rosa & Rosinha)', dia: 1, mes: 1 },
  { nome: 'Délio (Délio & Delinha)', dia: 12, mes: 2 },
  { nome: 'Delinha (Délio & Delinha)', dia: 23, mes: 3 },
  { nome: 'Célia (Célia & Celma)', dia: 4, mes: 4 },
  { nome: 'Celma (Célia & Celma)', dia: 15, mes: 5 },
  { nome: 'Roberto (Roberto e Meirinho)', dia: 26, mes: 6 },
  { nome: 'Meirinho (Roberto e Meirinho)', dia: 7, mes: 7 },
  { nome: 'Rayssa (Rayssa & Ravel)', dia: 18, mes: 8 },
  { nome: 'Ravel (Rayssa & Ravel)', dia: 29, mes: 9 },
  { nome: 'Abel (Abel & Caim)', dia: 10, mes: 10 },
  { nome: 'Caim (Abel & Caim)', dia: 21, mes: 11 },
  { nome: 'Alan (Alan & Aladim)', dia: 2, mes: 12 },
  { nome: 'Aladim (Alan & Aladim)', dia: 13, mes: 1 },
  { nome: 'Belmonte (Belmonte & Amaraí)', dia: 24, mes: 2 },
  { nome: 'Amaraí (Belmonte & Amaraí)', dia: 5, mes: 3 },
  { nome: 'Cacique (Cacique & Pajé)', dia: 16, mes: 4 },
  { nome: 'Pajé (Cacique & Pajé)', dia: 27, mes: 5 },
  { nome: 'Craveiro (Craveiro & Cravinho)', dia: 8, mes: 6 },
  { nome: 'Cravinho (Craveiro & Cravinho)', dia: 19, mes: 7 },
  { nome: 'Daniel (Daniel & Samuel)', dia: 2, mes: 8 },
  { nome: 'Samuel (Daniel & Samuel)', dia: 11, mes: 9 },
  { nome: 'Delmir (Delmir & Delmon)', dia: 22, mes: 10 },
  { nome: 'Delmon (Delmir & Delmon)', dia: 3, mes: 11 },
  { nome: 'Di Paullo (Di Paullo & Paulino)', dia: 14, mes: 12 },
  { nome: 'Paulino (Di Paullo & Paulino)', dia: 25, mes: 1 },
  { nome: 'Divisor (Divisor & Consciente)', dia: 6, mes: 2 },
  { nome: 'Consciente (Divisor & Consciente)', dia: 17, mes: 3 },
  { nome: 'Duduca (Duduca & Dalvan)', dia: 28, mes: 4 },
  { nome: 'Dalvan (Duduca & Dalvan)', dia: 9, mes: 5 },
  { nome: 'Falcão (Felipe & Falcão)', dia: 20, mes: 6 },
  { nome: 'Gilberto (Gilberto & Gilmar)', dia: 1, mes: 7 },
  { nome: 'Gilmar (Gilberto & Gilmar)', dia: 12, mes: 8 },
  { nome: 'Jean (Jean & Marcos)', dia: 23, mes: 9 },
  { nome: 'Marcos (Jean & Marcos)', dia: 4, mes: 10 },
  { nome: 'Joaquim (Joaquim & Manuel)', dia: 15, mes: 11 },
  { nome: 'Manuel (Joaquim & Manuel)', dia: 26, mes: 12 },
  { nome: 'Léo Canhoto (Léo Canhoto & Robertinho)', dia: 7, mes: 1 },
  { nome: 'Robertinho (Léo Canhoto & Robertinho)', dia: 18, mes: 2 },
  { nome: 'Lucas (Lucas & Luan)', dia: 29, mes: 3 },
  { nome: 'Luan (Lucas & Luan)', dia: 10, mes: 4 },
  { nome: 'Mandi (Mandi & Sorocabinha)', dia: 21, mes: 5 },
  { nome: 'Sorocabinha (Mandi & Sorocabinha)', dia: 2, mes: 6 },
  { nome: 'Manu (Manu e Rafael)', dia: 13, mes: 7 },
  { nome: 'Rafael (Manu e Rafael)', dia: 24, mes: 8 },
  { nome: 'Marlon (Marlon & Maicon)', dia: 5, mes: 9 },
  { nome: 'Maicon (Marlon & Maicon)', dia: 16, mes: 10 },
  { nome: 'Matogrosso (Matogrosso & Mathias)', dia: 27, mes: 11 },
  { nome: 'Mathias (Matogrosso & Mathias)', dia: 8, mes: 12 },
  { nome: 'Maurício (Maurício & Mauri)', dia: 19, mes: 1 },
  { nome: 'Mauri (Maurício & Mauri)', dia: 2, mes: 2 },
  { nome: 'May (May e Gabi)', dia: 11, mes: 3 },
  { nome: 'Gabi (May e Gabi)', dia: 22, mes: 4 },
  { nome: 'Mayck (Mayck & Lyan)', dia: 3, mes: 5 },
  { nome: 'Lyan (Mayck & Lyan)', dia: 14, mes: 6 },
  { nome: 'Nhô Belarmino (Nhô Belarmino & Nhá Gabriela)', dia: 25, mes: 7 },
  { nome: 'Nhá Gabriela (Nhô Belarmino & Nhá Gabriela)', dia: 6, mes: 8 },
  { nome: 'Osmar (Osmar & Osmailson)', dia: 17, mes: 9 },
  { nome: 'Osmailson (Osmar & Osmailson)', dia: 28, mes: 10 },
  { nome: 'Praião (Praião & Prainha)', dia: 9, mes: 11 },
  { nome: 'Prainha (Praião & Prainha)', dia: 20, mes: 12 },
  { nome: 'Zé Fortuna (Zé Fortuna & Pitangueira)', dia: 1, mes: 1 },
  { nome: 'Pitangueira (Zé Fortuna & Pitangueira)', dia: 12, mes: 2 },
  { nome: 'Zé Mulato (Zé Mulato & Cassiano)', dia: 23, mes: 3 },
  { nome: 'Cassiano (Zé Mulato & Cassiano)', dia: 4, mes: 4 },
  { nome: 'Althair (Althair & Alexandre)', dia: 15, mes: 5 },
  { nome: 'Alexandre (Althair & Alexandre)', dia: 26, mes: 6 },
  { nome: 'André (André & Adriano)', dia: 7, mes: 7 },
  { nome: 'Adriano (André & Adriano)', dia: 18, mes: 8 },
  { nome: 'Andrade (André & Andrade)', dia: 29, mes: 9 },
  { nome: 'Bob (Bob & Robison)', dia: 10, mes: 10 },
  { nome: 'Robison (Bob & Robison)', dia: 21, mes: 11 },
  { nome: 'Brenno (Brenno & Matheus)', dia: 2, mes: 12 },
  { nome: 'Matheus (Brenno & Matheus)', dia: 13, mes: 1 },
  { nome: 'Caçula (Caçula e Marinheiro)', dia: 24, mes: 2 },
  { nome: 'Marinheiro (Caçula e Marinheiro)', dia: 5, mes: 3 },
  { nome: 'Cezar (Cezar & Paulinho)', dia: 16, mes: 4 },
  { nome: 'Paulinho (Cezar & Paulinho)', dia: 27, mes: 5 },
  { nome: 'Chico Rey (Chico Rey & Paraná)', dia: 8, mes: 6 },
  { nome: 'Paraná (Chico Rey & Paraná)', dia: 19, mes: 7 },
  { nome: 'Cleiton (Cleiton & Camargo)', dia: 2, mes: 8 },
  { nome: 'Camargo (Cleiton & Camargo)', dia: 11, mes: 9 },
  { nome: 'Durval (Durval & Davi)', dia: 22, mes: 10 },
  { nome: 'Davi (Durval & Davi)', dia: 3, mes: 11 },
  { nome: 'Felipe (Felipe & Rodrigo)', dia: 14, mes: 12 },
  { nome: 'Rodrigo (Felipe & Rodrigo)', dia: 25, mes: 1 },
  { nome: 'Goiano (Goiano e Paranaense)', dia: 6, mes: 2 },
  { nome: 'Paranaense (Goiano e Paranaense)', dia: 17, mes: 3 },
  { nome: 'Juan Marcus (Juan Marcus & Vinícius)', dia: 28, mes: 4 },
  { nome: 'Vinícius (Juan Marcus & Vinícius)', dia: 9, mes: 5 },
  { nome: 'Luizinho (Luizinho e Limeira)', dia: 20, mes: 6 },
  { nome: 'Limeira (Luizinho e Limeira)', dia: 1, mes: 7 },
  { nome: 'Pedro (Pedro & Thiago)', dia: 12, mes: 8 },
  { nome: 'Thiago (Pedro & Thiago)', dia: 23, mes: 9 },
  { nome: 'Prima Miranda 1 (Primas Miranda)', dia: 4, mes: 10 },
  { nome: 'Prima Miranda 2 (Primas Miranda)', dia: 15, mes: 11 },
  { nome: 'Zazá (Zazá & Zezé)', dia: 26, mes: 12 },
  { nome: 'Zezé (Zazá & Zezé)', dia: 7, mes: 1 },
  { nome: 'Bruno (Bruno & Barretto)', dia: 18, mes: 2 },
  { nome: 'Barretto (Bruno & Barretto)', dia: 29, mes: 3 },
  { nome: 'Bruninho (Bruninho & Davi)', dia: 10, mes: 4 },
  { nome: 'Davi (Bruninho & Davi)', dia: 21, mes: 5 },
  { nome: 'Conrado (Conrado & Aleksandro)', dia: 2, mes: 6 },
  { nome: 'Aleksandro (Conrado & Aleksandro)', dia: 13, mes: 7 },
  { nome: 'Cleber (Cleber & Cauan)', dia: 24, mes: 8 },
  { nome: 'Cauan (Cleber & Cauan)', dia: 5, mes: 9 },
  { nome: 'Clayton (Clayton & Romário)', dia: 16, mes: 10 },
  { nome: 'Romário (Clayton & Romário)', dia: 27, mes: 11 },
  { nome: 'César Menotti (César Menotti & Fabiano)', dia: 8, mes: 12 },
  { nome: 'Fabiano (César Menotti & Fabiano)', dia: 19, mes: 1 },
  { nome: 'Camila (Camila & Haniel)', dia: 2, mes: 2 },
  { nome: 'Haniel (Camila & Haniel)', dia: 11, mes: 3 },
  { nome: 'Cácio (Cácio & Marcos)', dia: 22, mes: 4 },
  { nome: 'Marcos (Cácio & Marcos)', dia: 3, mes: 5 },
  { nome: 'Day (Day & Lara)', dia: 14, mes: 6 },
  { nome: 'Lara (Day & Lara)', dia: 25, mes: 7 },
  { nome: 'Dom Vittor (Dom Vittor & Gustavo)', dia: 6, mes: 8 },
  { nome: 'Gustavo (Dom Vittor & Gustavo)', dia: 17, mes: 9 },
  { nome: 'Diego (Diego & Victor Hugo)', dia: 28, mes: 10 },
  { nome: 'Victor Hugo (Diego & Victor Hugo)', dia: 9, mes: 11 },
  { nome: 'George Henrique (George Henrique & Rodrigo)', dia: 20, mes: 12 },
  { nome: 'Rodrigo (George Henrique & Rodrigo)', dia: 1, mes: 1 },
  { nome: 'Zé Ricardo (Zé Ricardo & Thiago)', dia: 12, mes: 2 },
  { nome: 'Thiago (Zé Ricardo & Thiago)', dia: 23, mes: 3 },
  { nome: 'André (André e Felipe)', dia: 4, mes: 4 },
  { nome: 'Felipe (André e Felipe)', dia: 15, mes: 5 },
  { nome: 'Breno (Breno & Caio Cesar)', dia: 26, mes: 6 },
  { nome: 'Caio Cesar (Breno & Caio Cesar)', dia: 7, mes: 7 },
  { nome: 'Canção (Canção & Louvor)', dia: 18, mes: 8 },
  { nome: 'Louvor (Canção & Louvor)', dia: 29, mes: 9 },
  { nome: 'Henrique (Henrique & Juliano)', dia: 10, mes: 10 },
  { nome: 'Juliano (Henrique & Juliano)', dia: 21, mes: 11 },
  { nome: 'Hugo (Hugo & Guilherme)', dia: 2, mes: 12 },
  { nome: 'Guilherme (Hugo & Guilherme)', dia: 13, mes: 1 },
  { nome: 'Guilherme (Guilherme & Benuto)', dia: 24, mes: 2 },
  { nome: 'Benuto (Guilherme & Benuto)', dia: 5, mes: 3 },
  { nome: 'Israel (Israel & Rodolffo)', dia: 16, mes: 4 },
  { nome: 'Rodolffo (Israel & Rodolffo)', dia: 27, mes: 5 },
  { nome: 'Jorge (Jorge & Mateus)', dia: 8, mes: 6 },
  { nome: 'Mateus (Jorge & Mateus)', dia: 19, mes: 7 },
  { nome: 'João Neto (João Neto & Frederico)', dia: 2, mes: 8 },
  { nome: 'Frederico (João Neto & Frederico)', dia: 11, mes: 9 },
  { nome: 'João Carreiro (João Carreiro & Capataz)', dia: 22, mes: 10 },
  { nome: 'Leandro (Leandro & Romário)', dia: 3, mes: 11 },
  { nome: 'Romário (Leandro & Romário)', dia: 14, mes: 12 },
  { nome: 'Maria Cecília (Maria Cecília & Rodolfo)', dia: 25, mes: 1 },
  { nome: 'Rodolfo (Maria Cecília & Rodolfo)', dia: 6, mes: 2 },
  { nome: 'Maiara (Maiara & Maraisa)', dia: 17, mes: 3 },
  { nome: 'Maraisa (Maiara & Maraisa)', dia: 28, mes: 4 },
  { nome: 'Marcelinho de Lima (Marcelinho de Lima & Camargo)', dia: 9, mes: 5 },
  { nome: 'Camargo (Marcelinho de Lima & Camargo)', dia: 20, mes: 6 },
  { nome: 'Marcos (Marcos & Belutti)', dia: 1, mes: 7 },
  { nome: 'Belutti (Marcos & Belutti)', dia: 12, mes: 8 },
  { nome: 'Matheus (Matheus & Kauan)', dia: 23, mes: 9 },
  { nome: 'Kauan (Matheus & Kauan)', dia: 4, mes: 10 },
  { nome: 'Maycon (Maycon & Vinícius)', dia: 15, mes: 11 },
  { nome: 'Vinícius (Maycon & Vinícius)', dia: 26, mes: 12 },
  { nome: 'Pedro Paulo (Pedro Paulo & Matheus)', dia: 7, mes: 1 },
  { nome: 'Matheus (Pedro Paulo & Matheus)', dia: 18, mes: 2 },
  { nome: 'Simone (Simone & Simaria)', dia: 29, mes: 3 },
  { nome: 'Simaria (Simone & Simaria)', dia: 10, mes: 4 },
  { nome: 'Thaeme (Thaeme & Thiago)', dia: 21, mes: 5 },
  { nome: 'Thiago (Thaeme & Thiago)', dia: 2, mes: 6 },
  { nome: 'Victor (Victor & Leo)', dia: 13, mes: 7 },
  { nome: 'Leo (Victor & Leo)', dia: 24, mes: 8 },
  { nome: 'Zé Henrique (Zé Henrique & Gabriel)', dia: 5, mes: 9 },
  { nome: 'Gabriel (Zé Henrique & Gabriel)', dia: 16, mes: 10 },
  { nome: 'Zé Neto (Zé Neto & Cristiano)', dia: 27, mes: 11 },
  { nome: 'Cristiano (Zé Neto & Cristiano)', dia: 8, mes: 12 },
  // === Complemento para 1000 (nomes reais - Wikipédia e referências) ===
  { nome: 'Mangabinha', dia: 19, mes: 1 },
  { nome: 'Mano Júnior', dia: 30, mes: 2 },
  { nome: 'Manu Bahtidão', dia: 11, mes: 3 },
  { nome: 'Marcelo Aguiar', dia: 22, mes: 4 },
  { nome: 'Marcelo Costa', dia: 3, mes: 5 },
  { nome: 'Marcelo Justino de Moraes', dia: 14, mes: 6 },
  { nome: 'Marciano (cantor)', dia: 25, mes: 7 },
  { nome: 'Marcos (cantor)', dia: 6, mes: 8 },
  { nome: 'Maria Izabel', dia: 17, mes: 9 },
  { nome: 'Mariangêla Zan', dia: 28, mes: 10 },
  { nome: 'Mateus Liduário', dia: 9, mes: 11 },
  { nome: 'Maurílio Delmont', dia: 20, mes: 12 },
  { nome: 'Mila (cantora)', dia: 1, mes: 1 },
  { nome: 'Milionário (cantor)', dia: 12, mes: 2 },
  { nome: 'Munhoz (cantor)', dia: 23, mes: 3 },
  { nome: 'Mariano (cantor)', dia: 4, mes: 4 },
  { nome: 'Murilo Huff', dia: 15, mes: 5 },
  { nome: 'Negro Cosmo', dia: 26, mes: 6 },
  { nome: 'Nenê do cururu', dia: 7, mes: 7 },
  { nome: 'Nhá Fia', dia: 18, mes: 8 },
  { nome: 'Nhá Zefa', dia: 29, mes: 9 },
  { nome: 'Nhô Pai', dia: 10, mes: 10 },
  { nome: 'Nonô Basílio', dia: 21, mes: 11 },
  { nome: 'Paraíso (cantor)', dia: 2, mes: 12 },
  { nome: 'Pardinho (cantor)', dia: 13, mes: 1 },
  { nome: 'Parrerito', dia: 24, mes: 2 },
  { nome: 'Paula Mattos', dia: 5, mes: 3 },
  { nome: 'Paulo Ayzen', dia: 16, mes: 4 },
  { nome: 'Pedro Leonardo', dia: 27, mes: 5 },
  { nome: 'Rafael Scan', dia: 8, mes: 6 },
  { nome: 'Raffael Machado', dia: 19, mes: 7 },
  { nome: 'Ravel (cantor)', dia: 2, mes: 8 },
  { nome: 'Rayssa Peres', dia: 11, mes: 9 },
  { nome: 'Renan Cardoso', dia: 22, mes: 10 },
  { nome: 'Renner Reis', dia: 3, mes: 11 },
  { nome: 'Rick Sollo', dia: 14, mes: 12 },
  { nome: 'Roberto Paiva', dia: 25, mes: 1 },
  { nome: 'Ronaldo Viola', dia: 6, mes: 2 },
  { nome: 'Sandro Coelho', dia: 17, mes: 3 },
  { nome: 'Sílvio Brito', dia: 28, mes: 4 },
  { nome: 'Sorocaba (cantor)', dia: 9, mes: 5 },
  { nome: 'Sula Mazurega', dia: 20, mes: 6 },
  { nome: 'Terry Winter', dia: 1, mes: 7 },
  { nome: 'Thales Lessa', dia: 12, mes: 8 },
  { nome: 'Thiago Bertoldo', dia: 23, mes: 9 },
  { nome: 'Thiago Brava', dia: 4, mes: 10 },
  { nome: 'Valéria Barros', dia: 15, mes: 11 },
  { nome: 'Victor Chaves', dia: 26, mes: 12 },
  { nome: 'Voninho', dia: 7, mes: 1 },
  { nome: 'Wagner Barreto', dia: 18, mes: 2 },
  { nome: 'Wanessa Camargo', dia: 29, mes: 3 },
  { nome: 'Yasmin Santos', dia: 10, mes: 4 },
  { nome: 'Zazá (cantor)', dia: 21, mes: 5 },
  { nome: 'Zé do Rancho', dia: 2, mes: 6 },
  { nome: 'Bruno (cantor)', dia: 13, mes: 7 },
  { nome: 'Carmen Silva (cantora)', dia: 24, mes: 8 },
  { nome: 'Dalvan (cantor)', dia: 5, mes: 9 },
  { nome: 'Daniel (cantor)', dia: 16, mes: 10 },
  { nome: 'Jayne (cantora)', dia: 27, mes: 11 },
  { nome: 'João Paulo (cantor)', dia: 8, mes: 12 },
  { nome: 'Leandro (cantor)', dia: 19, mes: 1 },
  { nome: 'Leonardo (cantor)', dia: 2, mes: 2 },
  { nome: 'Marcos (cantor)', dia: 11, mes: 3 },
  { nome: 'Milionário (cantor)', dia: 22, mes: 4 },
  { nome: 'Simaria', dia: 5, mes: 5 },
  { nome: 'Simone Mendes', dia: 16, mes: 6 },
  { nome: 'Thaeme', dia: 27, mes: 7 },
  { nome: 'Zé Neto (cantor)', dia: 8, mes: 8 },
  { nome: 'Chitãozinho', dia: 9, mes: 9 },
  { nome: 'Xororó', dia: 20, mes: 10 },
  { nome: 'Leandro & Romário', dia: 1, mes: 11 },
  { nome: 'Lucas & Matheus', dia: 12, mes: 12 },
  { nome: 'Munhoz & Mariano', dia: 23, mes: 1 },
  { nome: 'Teixeirinha', dia: 4, mes: 2 },
  { nome: 'Mary Terezinha', dia: 15, mes: 3 },
  { nome: 'Alemão do Forró', dia: 26, mes: 4 },
  { nome: 'Bonde do Forró', dia: 7, mes: 5 },
  { nome: 'Banda XCalypso', dia: 18, mes: 6 },
  { nome: 'Companhia do Calypso', dia: 29, mes: 7 },
  { nome: 'Os Filhos de Goiás', dia: 10, mes: 8 },
  { nome: 'Nechivile', dia: 21, mes: 9 },
  { nome: 'Trio Parada Dura', dia: 2, mes: 10 },
  { nome: 'Rick & Renner', dia: 13, mes: 11 },
  { nome: 'Rionegro & Solimões', dia: 24, mes: 12 },
  { nome: 'Tonico & Tinoco', dia: 5, mes: 1 },
  { nome: 'Tião Carreiro & Pardinho', dia: 16, mes: 2 },
  { nome: 'Chrystian & Ralf', dia: 27, mes: 3 },
  { nome: 'Leandro & Leonardo', dia: 8, mes: 4 },
  { nome: 'Gian & Giovani', dia: 19, mes: 5 },
  { nome: 'Gino & Geno', dia: 2, mes: 6 },
  { nome: 'Lourenço & Lourival', dia: 11, mes: 7 },
  { nome: 'Vieira & Vieirinha', dia: 22, mes: 8 },
  { nome: 'Palmeira & Luizinho', dia: 3, mes: 9 },
  { nome: 'Pedro Bento & Zé da Estrada', dia: 14, mes: 10 },
  { nome: 'Teodoro & Sampaio', dia: 25, mes: 11 },
  { nome: 'Tibagi & Miltinho', dia: 6, mes: 12 },
  { nome: 'Wilson & Soraia', dia: 17, mes: 1 },
  { nome: 'Sandro & Gustavo', dia: 28, mes: 2 },
  { nome: 'Rosa & Rosinha', dia: 9, mes: 3 },
  { nome: 'Délio & Delinha', dia: 20, mes: 4 },
  { nome: 'Roberto e Meirinho', dia: 1, mes: 5 },
  { nome: 'Rayssa & Ravel', dia: 12, mes: 6 },
  { nome: 'Abel & Caim', dia: 23, mes: 7 },
  { nome: 'Alan & Aladim', dia: 4, mes: 8 },
  { nome: 'Belmonte & Amaraí', dia: 15, mes: 9 },
  { nome: 'Cacique & Pajé', dia: 26, mes: 10 },
  { nome: 'Craveiro & Cravinho', dia: 7, mes: 11 },
  { nome: 'Daniel & Samuel', dia: 18, mes: 12 },
  { nome: 'Delmir & Delmon', dia: 29, mes: 1 },
  { nome: 'Di Paullo & Paulino', dia: 10, mes: 2 },
  { nome: 'Divisor & Consciente', dia: 21, mes: 3 },
  { nome: 'Duduca & Dalvan', dia: 2, mes: 4 },
  { nome: 'Felipe & Falcão', dia: 13, mes: 5 },
  { nome: 'Gilberto & Gilmar', dia: 24, mes: 6 },
  { nome: 'Jean & Marcos', dia: 5, mes: 7 },
  { nome: 'Joaquim & Manuel', dia: 16, mes: 8 },
  { nome: 'Léo Canhoto & Robertinho', dia: 27, mes: 9 },
  { nome: 'Liu & Léu', dia: 8, mes: 10 },
  { nome: 'Lucas & Luan', dia: 19, mes: 11 },
  { nome: 'Luizinho e Limeira', dia: 2, mes: 12 },
  { nome: 'Mandi & Sorocabinha', dia: 11, mes: 1 },
  { nome: 'Manu e Rafael', dia: 22, mes: 2 },
  { nome: 'Marlon & Maicon', dia: 3, mes: 3 },
  { nome: 'Matogrosso & Mathias', dia: 14, mes: 4 },
  { nome: 'Maurício & Mauri', dia: 25, mes: 5 },
  { nome: 'May e Gabi', dia: 6, mes: 6 },
  { nome: 'Mayck & Lyan', dia: 17, mes: 7 },
  { nome: 'Nhô Belarmino & Nhá Gabriela', dia: 28, mes: 8 },
  { nome: 'Os Levitas', dia: 9, mes: 9 },
  { nome: 'Os Nonatos', dia: 20, mes: 10 },
  { nome: 'Osmar & Osmailson', dia: 1, mes: 11 },
  { nome: 'Pardinho & Pardal', dia: 12, mes: 12 },
  { nome: 'Pedro & Thiago', dia: 23, mes: 1 },
  { nome: 'Pena Branca & Xavantinho', dia: 4, mes: 2 },
  { nome: 'Praião & Prainha', dia: 15, mes: 3 },
  { nome: 'Primas Miranda', dia: 26, mes: 4 },
  { nome: 'Raul Torres & Florêncio', dia: 7, mes: 5 },
  { nome: 'Zé Fortuna & Pitangueira', dia: 18, mes: 6 },
  { nome: 'Zé Mulato & Cassiano', dia: 29, mes: 7 },
  { nome: 'Althair & Alexandre', dia: 10, mes: 8 },
]

